package.json

now the favicon makes it to the npm package and the server actually runs

fix missing favicon from npm package

---

README.md
docs/pg-jwt-spec.md
package.json
scripts/test.sh
src/createServer.js
src/main.js
src/promisify.js
tests/createServer.test.js
tests/integration/index.test.js

This PR's goal is to add authorization and optional authentication to PostGraphQL. As of the opening of this issue I have only added authorization support using JWTs. Look at the tests, look at the readme, and look at [this](https://github.com/calebmer/postgraphql/blob/feat/auth/docs/pg-jwt-spec.md) specification and tell me if you like this authorization schema. Authentication (creating tokens) will be decided later on.

Authorization and authentication

---

src/postgres/getCatalog.js

Addresses https://github.com/calebmer/postgraphql/issues/12
Supersedes https://github.com/calebmer/postgraphql/pull/13

Prevent `error: operator is not unique: smallint[] @> smallint[]`

---

examples/forum/schema.sql
src/graphql/getColumnType.js
tests/graphql/getColumnType.test.js

Fix for https://github.com/calebmer/postgraphql/issues/35
Enum types get cashed using default memoize resolver. Removed schema validation error

fix(graphql): enum types get cached (#35)

---

src/graphql/mutation/createUpdateMutationField.js

Otherwise boolean and null values get coerced which will render
undesired result.

fix(graphql): explicitly check input values for undefined

---

src/graphql/createViewerField.js
src/graphql/mutation/createDeleteMutationField.js
src/graphql/mutation/createInsertMutationField.js
src/graphql/mutation/createProcedureMutationField.js
src/graphql/mutation/createUpdateMutationField.js
src/graphql/mutation/getPayloadFields.js
src/graphql/mutation/getPayloadInterface.js
src/graphql/query/createNodeQueryField.js
src/graphql/query/createQueryFields.js
src/graphql/query/createQueryType.js
src/graphql/query/createViewerField.js
src/symbols.js
tests/integration/fixtures/viewer-mutation.graphql
tests/integration/fixtures/viewer-mutation.json
tests/integration/fixtures/viewer-query.graphql
tests/integration/fixtures/viewer-query.json

Adds a Relay viewer field to the root query type and to all of the mutation payloads. @hardchor, @msimulcik is this what you’re looking for?
Closes #38 and maybe #43.

Add Relay viewer field

---

src/graphql/getType.js
src/postgres/catalog.js
src/postgres/getCatalog.js
tests/graphql/getType.test.js
tests/helpers.js
tests/postgres/getCatalog.test.js

Domains are mapped to `GraphQLString` by default, this patch retrieve domain's base type to map them to the proper GraphQL types. Also supports domains of domains.

Add support for user defined domains

---

examples/kitchen-sink/schema.sql
src/graphql/resolveTableSingle.js
tests/integration/fixtures/null-foreign-key.graphql
tests/integration/fixtures/null-foreign-key.json

Foreign keys that are of type `int` are converted to strings [(diff)](https://github.com/calebmer/postgraphql/compare/master...ferdinandsalis:fix-resolve-single?expand=1#diff-0f601b95d640a7e7b90036b6dfb374fbL51). I know this is intended since `any`’s righthand side expects an array expression (if my research was correct). However when a foreign key is null it is interpreted as a string and result in the following error: `error: invalid input syntax for integer`.
I have yet to add a test. Though I am not sure where ☺️.

fix(resolve): check for empty string in query values

---

examples/kitchen-sink/schema.sql
src/graphql/mutation/createMutationType.js
src/postgres/catalog.js
src/postgres/getCatalog.js
tests/helpers.js
tests/integration/fixtures/non-updatable-views-filtered.graphql
tests/integration/fixtures/non-updatable-views-filtered.json
tests/postgres/getCatalog.test.js

This is a rework of #53.
I will filter mutations to only show postgres objects that are updatable. This will hide views that are not auto updatable from the mutations graphql schema. 
It will also hide custom types, so the second part of this pr will add in custom types so that they can be used as input and output values of queries and mutations.

feat(postgres): only show mutations for types that are updatable.

---

examples/kitchen-sink/schema.sql
src/graphql/query/createAllNodeQueryField.js
src/graphql/query/createNodeQueryField.js
src/graphql/query/createQueryFields.js
src/graphql/query/createSingleQueryField.js
src/graphql/query/createTableQueryFields.js
src/graphql/resolveTableSingle.js
src/postgres/catalog.js
src/postgres/getCatalog.js
tests/graphql/query/createNodeQueryField.test.js
tests/integration/fixtures/unique-constraints.graphql
tests/integration/fixtures/unique-constraints.json
tests/postgres/getCatalog.test.js

Closes #67
Let the reviews, begin!

feat(graphql): add fields based on unique constraints

---

examples/kitchen-sink/schema.sql
src/graphql/getType.js
src/graphql/types.js

This is a hotfix to solve #88. I’m working on some refactors to the codebase which would make the “correct” solution possible. For now I want to deploy a fix as this is crashing APIs.
The correct implementation would be to split the type into both a `GraphQLObjectType` and a `GraphQLInputObjectType`.

Fix interval and other type handling

---

.travis.yml
examples/kitchen-sink/schema.sql
src/graphql/resolveConnection.js
src/graphql/types.js
tests/integration/fixtures/mutation-insert.json
tests/integration/fixtures/nodes.graphql
tests/integration/fixtures/nodes.json
tests/integration/fixtures/pagination.graphql
tests/integration/fixtures/procedure-query.graphql
tests/integration/fixtures/procedure-query.json

Fixes non-unique cursors by adding values for the primary key to the cursor and using that to select.
Closes https://github.com/calebmer/postgraphql/issues/93

fix(graphql): non-unique cursors

---

examples/kitchen-sink/schema.sql
src/graphql/types.js
tests/integration/fixtures/types.graphql
tests/integration/fixtures/types.json

JSON objects have been serializing incorrectly. This has been mentioned a couple of times like in https://github.com/calebmer/postgraphql/issues/116 or https://github.com/calebmer/postgraphql/pull/102.
This fixes the problem, but still doesn’t add arbitrary JSON to the tree as is advocated in https://github.com/calebmer/postgraphql/pull/102 :+1:

Fix JSON type serialization

---

docs/library.md
package.json
resources/introspection-watch.sql
resources/watch-fixtures.sql
scripts/dev
src/postgraphql/__tests__/postgraphql-test.js
src/postgraphql/cli.ts
src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js
src/postgraphql/http/createPostGraphQLHttpRequestHandler.d.ts
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/postgraphql.ts
src/postgraphql/watch/__tests__/watchPgSchemas-test.js
src/postgraphql/watch/watchPgSchemas.ts
src/postgres/introspection/introspectDatabase.ts

This PR adds watch functionality to PostGraphQL :tada:
When giving demonstrations of PostGraphQL I’d like to have a fast feedback cycle. Being able to have PostGraphQL open and watching in one window and a Postgres query input in the other while PostGraphQL automatically updates is a great way to get to a fast feedback cycle. I was going to just write a script, but instead I decided to just put it in the project :blush:
To use just pass in `--watch` and/or `watchPg: true` (depending on if you are using the CLI or the middleware). PostGraphQL will add an event trigger to your database (can only be done if you start PostGraphQL as a superuser), and whenever it gets a notification from that trigger PostGraphQL will automatically rebuild the schema. The next step is just to get GraphiQL to …

Add schema watch functionality to CLI and middleware

---

src/postgraphql/schema/createPostGraphQLSchema.ts

https://github.com/calebmer/postgraphql/issues/171
To quote the issue:
> When creating a postgraphql schema, when passed a `DATABASE_URL`, if you use `pgClient.release()` as done here:
>
> https://github.com/calebmer/postgraphql/blob/ad8dd3f9a142f4cd776cf9abb799d1b2f3bf8162/src/postgraphql/schema/createPostGraphQLSchema.ts#L46
>
> then the connection to postgres persists and the node process won't exit. Changing this to `pgClient.end()` solves the issue.
>
> ```js
> import {createPostGraphQLSchema} from 'postgraphql';
>
> const Schema = await createPostGraphQLSchema(process.env.DATABASE_URL, 'schema_data', {});
> ```
This PR fixes that :+1:

fix(postgraphql): fix create schema to end client after introspection

---

src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgres/inventory/addPgCatalogToInventory.ts

Found some errors that could use better error messages to avoid confusion in the future:
- Passing non-objects into the HTTP GraphQL endpoint. For example arrays, this may happen if your GraphQL client assumes query batching is supported.
- Using a relation on columns that don’t have a uniqueness constraint.
/cc @rojobuffalo, @benjie

Fix error messages

---

src/postgraphql/__tests__/postgraphql-test.js
src/postgraphql/postgraphql.ts

Fixes https://github.com/calebmer/postgraphql/issues/184
/cc @calebthebrewer

Fix optional argument ordering

---

src/graphql/schema/__tests__/createMutationGqlField-test.js
src/graphql/schema/createMutationPayloadGqlType.ts
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationOperations-test.js.snap
src/postgraphql/__tests__/fixtures/queries/mutation-create.graphql
src/postgraphql/__tests__/fixtures/queries/mutation-delete.graphql
src/postgraphql/__tests__/fixtures/queries/mutation-update.graphql

Fixes https://github.com/calebmer/postgraphql/issues/188
In order to support selecting `Query` from `node` for Relay 1, the value of `Query` was required to be a symbol named `$$isQuery`. This wasn’t always the case, originally any value for the query was acceptable so mutations would just return `null` instead of the query value. This fixes that.
/cc @benjie

fix(graphql): fix mutation query field returning null

---

.travis.yml

This adds Postgres 9.5 support to the Travis CI tests

feat(ci): run against multiple postgres versions

---

CONTRIBUTING.md
package.json
src/postgraphql/__tests__/postgraphqlIntegrationOperations-test.js
src/postgraphql/__tests__/postgraphqlIntegrationSchema-test.js
src/postgres/introspection/__tests__/introspectDatabase-test.js
src/postgres/inventory/collection/__tests__/PgCollection-test.js
src/postgres/inventory/collection/__tests__/PgCollectionKey-test.js

It seems that CI isn't the only place that has troubles running the tests without timeouts, my ancient iMac can't complete them as fast as necessary either. To that end I've removed the CI clauses and extended the timeouts to 20 seconds which now means that none of the tests timeout on my machine any more.
I've derived from the commit messages that you're using the same format as AngularJS/Karma; I found it more pleasant to link to the Karma page rather than google docs so I've linked there. I used the following command to extract the accepted types/scopes, and then filtered them down for consistency
```
git log --pretty='%s' | grep ':' | sed 's/:.*//' | sort -u
```
Since we use both doc and docs, test and tests, I have picked the one that I feel is more consistent with the upstream …

Help contributors get started

---

src/postgres/__tests__/fixtures/withPgClient.ts

As @benjie mentioned in the Gitter chat, tests in this repo have probably been failing thanks to daylight savings time lol :blush:
This should fix the problem by setting our tests to run in Eastern Daylight Time instead of oscillating between Eastern Daylight Time and Eastern Standard Time, I think. Honestly, I just looked up the [Postgres timezone](https://www.postgresql.org/docs/7.2/static/timezones.html) docs and made the change through GitHub, hope this works :wink:

Fix daylight savings time failures

---

docs/default-role.md

`--connection` parameter needs to be present for connection string otherwise default connection is made

Fixed command examples

---

src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationOperations-test.js.snap
src/postgraphql/__tests__/fixtures/queries/mutation-create.graphql
src/postgraphql/__tests__/fixtures/queries/mutation-update.graphql

Closes https://github.com/calebmer/postgraphql/issues/108
This functionality has worked since the release of GraphQL `0.8.*` thanks to @langpavel’s work, these tests just ensure that null with creates and updates works as expected to prevent future regression.

Add tests for create/update w/ null

---

scripts/build
scripts/dev
scripts/postinstall
src/postgraphql/graphiql/src/components/PostGraphiQL.js
src/postgraphql/graphiql/src/index.js
src/postgraphql/http/__tests__/setupServerSentEvents-test.js
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/http/setupServerSentEvents.js

Note this merges into the `feat/extend-graphiql-2` branch (not master).
- switches from port 5001 (which conflicted for me so likely will for others) to 5783
- adds a postinstall script to build/dev that detects if the graphiql dependencies have ever been installed and if not installs them (does NOT handle later updates, but it's a good first stab I think)
- fixes a minor issue where the background process killer is too noisy

Tweaks to GraphiQL PR

---

CONTRIBUTING.md

* correct typo on 'scripts/run-kitchen-sink-stream' to 'scripts/run-kitchen-sink-sql'
* standardize PostGraphQL camel case name throughout Contribution file
* add 'npm install' as one of the steps for setting up the dev environment
* change 'doc' to 'docs' on the type initial list

fix(docs): correct contribution file

---

src/graphql/schema/collection/getCollectionGqlType.ts
src/graphql/schema/node/createNodeFieldEntry.ts
src/graphql/schema/node/getNodeInterfaceType.ts

A small refactor that removes the main reason we need an `isTypeOf` function in collection types. This gives us a super small performance win, but also makes it easier to implement computed column performance wins and selective column selections.

Remove isTypeOf check from collection types

---

src/postgraphql/http/createPostGraphQLHttpRequestHandler.js

The HTTP error handler was looking in `error.status` for the status code to return to the client, but some error codes were being set in `error.statusCode`.
Fixes half the error reported in #287 where the JWT error throws a 500 rather than a 403.

fix(postgraphql): try getting error code from error.statusCode before falling back to 500

---

package.json

See https://github.com/calebmer/postgraphql/pull/319 and #321; this is clearly breaking things for people who want to get started with postgraphql, so we should get a simple fix out ASAP before fixing it more permanently by renaming `__id` later. 
@calebmer can you release this one commit as a bugfix release?

fix(deps): restrict graphql version range

---

src/postgraphql/cli.ts

This PR fixes two tiny issues I have had with the connection string option:
1) it gives a little demo in the help output
2) it shows the default port of postgres in case the connection string doesn't support one

Better postgres Connection string support

---

src/postgres/inventory/type/scalar/pgFloatType.ts

Finally got around to figuring out what was wrong with the tests for me...
I'm concerned that the removal of commas might be localization dependent too, for example in continental Europe they tend to place commas where we place dots and vice versa; e.g. €1.234,56 - if this is the case for the money type then things are going to go wrong... 😜

fix(postgres): fix processing money type

---

examples/kitchen-sink/data.sql
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationOperations-test.js.snap
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationSchema-test.js.snap
src/postgraphql/__tests__/fixtures/queries/mutation-create.graphql
src/postgraphql/__tests__/fixtures/queries/procedure-mutation.graphql
src/postgraphql/__tests__/fixtures/queries/procedure-query.graphql
src/postgres/inventory/type/custom/pgBigIntType.ts
src/postgres/inventory/type/getTypeFromPgType.ts
src/postgres/inventory/type/scalar/pgStringType.ts

Fixes https://github.com/calebmer/postgraphql/issues/302
This PR makes it so that PostGraphQL no longer uses the native GraphQL `Int` type to represent big integers (as a big integer can be larger than `Int` allows). So instead we now have a `BigInt` type which serializes and deserializes as a string. It is a string because in JavaScript a big integer can be larger than what a number supports. To get around that limitation all big integers will be strings. If you’d like you can parse big integers on the client.
This is a breaking change I’ve wanted to make for a while, so now that we need a breaking change for https://github.com/calebmer/postgraphql/pull/327 I want to get this change into `3.x` as well.

Use a custom type for big integers

---

src/postgraphql/__tests__/withPostGraphQLContext-test.js
src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js
src/postgraphql/http/createPostGraphQLHttpRequestHandler.d.ts
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/postgraphql.ts
src/postgraphql/withPostGraphQLContext.ts

This pull request adds the `pgSettings` configuration parameter to `postgraphql` middleware function. With this parameter it is possible to set custom config values to the postgres connection. These settings can then be accessed via `current_setting('my.custom.setting')` in all stored procedures. This is analog to the usage of the `jwt.claims` settings but can be defined at middleware initialisation time.
I hope you like it.

feat(postgraphql): inject custom settings into the database

---

src/postgraphql/graphiql/src/components/PostGraphiQL.js

I'm using basic authentication on my postgraphql endpoint. This configures fetch() to pass along the browser's credentials, which seems to be the norm for other graphiql users like express-graphql:
https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js#L114
Based on my reading of the code, it doesn't appear that `jwtToken` is ever passed in, so I didn't test passing that in. But changing "credentials" to "include" shouldn't result in it being overwritten if it is passed in, according to the fetch spec:
https://fetch.spec.whatwg.org/#http-network-or-cache-fetch
"If httpRequest’s header list contains `Authorization`, then terminate these substeps."

fix(graphqli): pass along credentials in fetcher

---

scripts/build

Home directories with spaces in them (forced by companies that don't understand how usernames work) break building the project. Take it or leave it, but this fixes that.

Support spaces in folder name

---

examples/kitchen-sink/schema.sql
scripts/typecheck
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationMutations-test.js.snap
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationSchema-test.js.snap
src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationSchemaExport-test.js.snap
src/postgraphql/__tests__/fixtures/mutations/procedure-mutation.graphql
src/postgraphql/schema/procedures/PgProcedurePaginator.ts
src/postgraphql/schema/procedures/createPgProcedureFixtures.ts
src/postgraphql/schema/procedures/createPgProcedureMutationGqlFieldEntry.ts
src/postgraphql/schema/procedures/createPgProcedureObjectTypeGqlFieldEntry.ts
src/postgraphql/schema/procedures/createPgProcedureQueryGqlFieldEntry.ts
src/postgres/introspection/__tests__/__snapshots__/introspectDatabase-test.js.snap

Fixes https://github.com/postgraphql/postgraphql/issues/429
This PR adds support for procedures that return void as mutations _only_. I don’t see the point in supporting procedures that return void for queries, because if a procedure returns void the likely explanation for doing so is that the procedure is performing some kind of side effect which is not allowed in GraphQL queries. If you can think of a case where return void is good for queries, let us know and we can add support!

Support mutations that return void

---

examples/forum/TUTORIAL.md

It seems like the computed column functions must be prefixed by the table's name, not table first argument's name. I tried naming the first argument do something else and it still works. Is it a requirement indeed?

doc (examples) Clarify computed column function criteria

---

src/postgraphql/http/createPostGraphQLHttpRequestHandler.js

The documentation says "And if you don’t want authorization, just don’t set the --secret argument and PostGraphQL will ignore all authorization information!"
It turns out postgraphql _does_ read auth information and throws an error if the format is not as expected. This prevents folks from using the Authorization header for non-JWT, like Basic auth. 
#433 was my first go at this change.

fix(postgraphql): don't throw on auth header if auth not enabled

---

src/postgraphql/withPostGraphQLContext.ts

I noticed this issue when using the **authMiddleware** from https://github.com/nodkz/react-relay-network-layer 
authMiddleware provides the following functionality
> tokenRefreshPromise: - function(req, err) which must return promise or regular value with a new token. This function is called when server returns **401** status code. After receiving a new token, middleware re-run query to the server with it seamlessly for Relay.
However postgraphql only sends a 403 status code.  I was going to create a pull request for authMiddleware but after a bit of research I can see that postgrapqhl should really be sending a 401 in this case*.
Many people will be using authMiddleware with Relay, so this could make things easier all
*https://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unaut …

We should be sending a 401 status code not a 403 on expired token.

---

docs/cli.md
docs/library.md
examples/forum/TUTORIAL.md
src/postgraphql/__tests__/withPostGraphQLContext-test.js
src/postgraphql/cli.ts
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/postgraphql.ts
src/postgraphql/withPostGraphQLContext.ts

… from any location in the JWT, defaults to 'role' on the root of the JWT object.
When working with Auth0 as the source of the JWT it can be difficult to write directly to the root of the jwt (their rules engine allows writing to the jwt but it has to be namespaced with a url-like property name.)
I created this PR that allows you to specify a path in the jwt from which to set the pgRole; if unset it defaults to the current 'role' property on the root of the jwt.
Since this is my first commit I probably missed something, though I did add unit tests where appropriate, updated docs, ran all tests, (ran the linter) and tried to follow the commit guidelines.

feat(postgraphql): extract pgRole from arbitrary JWT path

---

package.json

locked version to <7.2.1 until we upgrade rest of code to typescript 2.2
there were some other warnings when I upgraded the typescript dependency to ^2.2.x  and I wasn't quite sure how to fix.  
If you force @types/jsonwebtoken to 7.2.1 you can see the compile error.
Alternative would be to update typescript dependency to 2.2 and fix the three compile warnings.

fix(ci) @types/jsonwebtoken >= 7.2.1 requires typescript 2.2 or higher

---

package.json
src/postgraphql/__tests__/postgraphql-test.js
src/postgraphql/postgraphql.ts

Changes the thrown error to simply a console warning.
Regarding #466 
Turns out it's sometimes valid to have jwtSecret but not jwtPgTypeIdentifier.

Change jwtPgTypeIdentifier error to warning; fix CI (upgrade GraphiQL/etc)

---

package.json
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js

`pgDefaultRole`, if set, overrides the `role` returned by `pgSettings`. We could fix this, but since this behaviour already existed it would be a breaking change (and have security implications besides!) so instead this version will throw if this invalid behaviour might take place.
In a later release we might let these options co-exist again (but the right way around!)

Avoid pgDefaultRole/pgSettings() clashes

---

docs/library.md
src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js
src/postgraphql/http/createPostGraphQLHttpRequestHandler.d.ts
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/postgraphql.ts

Add an optional parameter called `additionalGraphqlContextFromRequest` to the options object supplied to the postgraphile middleware [here](https://www.graphile.org/postgraphile/usage-library/#api-postgraphilepgconfig-schemaname-options)
This should be provided an async function which resolves to an object. It will be called upon graphql requests, and provided the incoming request object. The resultant object is then applied to the context passed to all graphql resolvers.
This will allow us to add extra information from the request into the graphql resolver context, which when writing custom plugins will be useful for instances such as personalisation or auth flows outside of postgres.
Cheers for the library, think it's awesome.

feat(postgraphql): Provide mechanism to add data to resolver context

---

src/postgraphql/__tests__/withPostGraphQLContext-test.js
src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js
src/postgraphql/withPostGraphQLContext.ts

~~For example, instead of an `undefined` pgSetting becoming `"undefined"` turn it into `null` so `set_config` can still accept it~~
Fixes: #566

feat(pgsettings): Only use settings of type string or number

---

src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js
src/postgraphql/http/createPostGraphQLHttpRequestHandler.d.ts
src/postgraphql/http/createPostGraphQLHttpRequestHandler.js
src/postgraphql/postgraphql.ts

feat(additionalGraphQLContextFromRequest): add res to callback

---

Dockerfile

GraphiQL produces error: Cannot use e "__Schema" from another module or realm. #677
Pin the version of graphql to < 0.12 in the package.json right before the npm build.

Fix GraphiQL dependency in dockerfile see #677

---

Dockerfile

This should decrease the docker image, because each RUN command creates new layer in docker image.
Image size reduction 278MB -> 142MB.

Remove middle layers from docker image

---

docs/library.md

This PR adds documentation for the optional `jwtAudiences` and `jwtRole` options for `withPostGraphQLContext`, which are similar to `postgraphql` options.
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>

docs(library): Add audiences / role documentation for withPostGraphQLContext

---

docs/library.md

Another tiny documentation fix: The `Pool` import is the default/unnamed export of the standalone `pg-pool` module as seen in the [docs](https://github.com/brianc/node-pg-pool/blob/master/README.md).
Signed-off-by: petetnt <pete.a.nykanen@gmail.com>

fix(docs): Fix pg-pool import in library.md

---

package.json
src/postgraphile/__tests__/__snapshots__/postgraphileIntegrationSchema-test.js.snap
src/postgraphile/__tests__/__snapshots__/postgraphileIntegrationSchemaExport-test.js.snap
src/postgraphile/__tests__/postgraphileIntegrationSchema-test.js
src/postgraphile/cli.ts
src/postgraphile/postgraphile.ts
yarn.lock

- `--legacy-json-uuid` - uses `Uuid` and `Json` over `UUID` and `JSON`
- `--no-setof-functions-contain-nulls` / `-N` - reduces nullables in the schema by promising functions that return setof compound types won't return a null in the middle of the results

feat: SQL perf++; CLI overhall; CLI opts to use Json/Uuid & reduce nullables

---

src/postgraphile/graphiql/src/components/PostGraphiQL.js

During development the server sometimes restarts; we want the GraphiQL schema to automatically re-inspect when this happens. Also tries to avoid killing GraphiQL when a non-compatible hot-load occurs.

feat(graphiql): auto-reinspect on reconnect (and better hot-load support)

---

package.json
src/postgraphile/http/setupServerSentEvents.js

Otherwise watching changes in GraphiQL doesn't work if you're using the Koa compress middleware.

fix(koa): don't compress server-sent events stream

---

src/postgraphile/http/createPostGraphileHttpRequestHandler.js

Koa sometimes seems to hang when loading GraphiQL; I've not been able to deliberately reproduce it. This seems to be solving it so far... Really we ought to replace `sendFile` with something Koa-friendly.

fix(koa): don't compress assets via send

---

src/postgraphile/cli.ts
src/postgraphile/postgraphile.ts

Because it turns out some people use PostGraphile in interesting ways (e.g. defining and/or granting permissions after the server starts) this would be too much of a breaking change.
RBAC will be ignored by default in v5, so it's recommended you explicitly use `--ignore-rbac` or `--no-ignore-rbac` depending on your preference to make your v5 transition easier.

fix: ignore RBAC by default, tweak CLI & library documentation

---

package.json
prettier.config.js
src/__tests__/utils/createTestInParallel.ts
src/__tests__/utils/withPgClient.ts
src/index.ts
src/interfaces.ts
src/postgraphile/__tests__/postgraphile-test.js
src/postgraphile/__tests__/postgraphileIntegrationQueries-test.js
src/postgraphile/__tests__/postgraphileIntegrationSchema-test.js
src/postgraphile/__tests__/withPostGraphileContext-test.js
src/postgraphile/cli.ts
src/postgraphile/extendedFormatError.ts
src/postgraphile/graphiql/src/components/PostGraphiQL.js
src/postgraphile/graphiql/src/index.js
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/koaMiddleware.ts
src/postgraphile/http/setupServerSentEvents.ts
src/postgraphile/index.ts
src/postgraphile/pluginHook.ts
src/postgraphile/postgraphile.ts
src/postgraphile/schema/exportPostGraphileSchema.ts
src/postgraphile/withPostGraphileContext.ts
src/postgres/inventory/pgClientFromContext.ts
tslint.json
yarn.lock

Prettier has been configured to apply minimal changes to the codebase; I'll follow this up with a PR that enables semicolons (🎉)
If you're checking this diff, you probably want to do so using `git diff -w --word-diff-regex=[^[:space:]]` so that it ignores *all* whitespace changes.

chore(lint): apply `prettier` against the codebase

---

prettier.config.js
src/__tests__/utils/createTestInParallel.ts
src/__tests__/utils/kitchenSinkSchemaSql.ts
src/__tests__/utils/pgPool.ts
src/__tests__/utils/printSchemaOrdered.js
src/__tests__/utils/withPgClient.ts
src/index.ts
src/interfaces.ts
src/postgraphile/__tests__/__mocks__/fs.js
src/postgraphile/__tests__/__mocks__/postgraphile-core.js
src/postgraphile/__tests__/postgraphile-test.js
src/postgraphile/__tests__/postgraphileIntegrationMutations-test.js
src/postgraphile/__tests__/postgraphileIntegrationQueries-test.js
src/postgraphile/__tests__/postgraphileIntegrationSchema-test.js
src/postgraphile/__tests__/postgraphileIntegrationSchemaExport-test.js
src/postgraphile/__tests__/withPostGraphileContext-test.js
src/postgraphile/cli.ts
src/postgraphile/extendedFormatError.ts
src/postgraphile/graphiql/src/components/PostGraphiQL.js
src/postgraphile/graphiql/src/index.js
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/koaMiddleware.ts
src/postgraphile/http/setupServerSentEvents.ts
src/postgraphile/index.ts
src/postgraphile/pluginHook.ts
src/postgraphile/postgraphile.ts
src/postgraphile/schema/exportPostGraphileSchema.ts
src/postgraphile/withPostGraphileContext.ts
src/postgres/inventory/pgClientFromContext.ts

This diff only contains semicolon changes (except for a few places where adding a semicolon caused the line to wrap, and thus whitespace trailing commas were added also).
You can confirm this with `git diff -w --word-diff-regex='[^[:space:]]' --patience` and `git diff -w --word-diff-regex='[^;]' --patience`

chore(lint): add semicolons (via `prettier`)

---

src/postgraphile/__tests__/withPostGraphileContext-test.js
src/postgraphile/withPostGraphileContext.ts

The rules are this:
If it's the `role` setting then the first of these will win:
1. Role from pgSettings
2. Role from JWT
3. Role from `pgDefaultRole`
Otherwise, the first of these will win:
1. JWT
2. pgSettings
I'll probably change this in v5.

chore(tests): enforce current behaviour when settings are provided by both JWT and pgSettings

---

scripts/dev
src/postgraphile/cli.ts

`postgraphile -A ''` should disable audience verification, but it didn't. Thanks for spotting the error, Daniel V 👍

fix(CLI): disabling JWT audience verification now possible

---

src/postgraphile/postgraphile.ts
src/postgraphile/withPostGraphileContext.ts

Previously options passed to `createPostGraphileHttpRequestHandler` when using PostGraphile as a library had not gone through options mangling so changes to them from plugins were not available in all areas.
(`pluginHook` is still alpha-quality.)

fix(hooks): ensure hooked options passed to createPostGraphileHttpRequestHandler

---

package.json
src/interfaces.ts
src/postgraphile/cli.ts
yarn.lock

`parentQueryBuilder` was added too late to be useful, move it back a step.

feat(deps): Upgrade postgraphile-core

---

README.md

Replaces img tags with its markdown analougue.
Fixes #886

fix: img tags in README.md

---

package.json
postgraphiql/src/components/PostGraphiQL.js
src/interfaces.ts
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/koaMiddleware.ts
yarn.lock

- Gets rid of `/_postgraphile/*` (backwards compatible for `/_postgraphile/stream` in case you hard-coded that (don't!))
- Stream URL now at `/graphql/stream`; but don't hard-code that - we set it in the `X-GraphQL-Event-Stream` header which you should use instead
- Switches to using `originalUrl` rather than `url` when processing the request
- `graphqlRoute` and `graphiqlRoute` are treated as *absolute* paths - i.e. `app.use('/path/to', postgraphile())` will **not** work, you need to do: `app.use('/path/to', postgraphile({graphqlRoute: '/path/to/graphql'}))`
- Even works with Koa/koa-mount
- Fixes incorrect type for `enableQueryBatching`

feat(http): support mounting on subroutes

---

examples/forum/schema.sql

to prevent error 
```
invalid input syntax for integer: "": {"response":{"errors":[{"message":"invalid input syntax for integer: \"\"","locations":[{"line":3,"column":9}],"path":["currentUser"]}],"data":{"currentUser":null},"status":200},"request":{"query":"\n      query {\n        currentUser {\n          emails\n          rowId\n        }\n      }\n    ","variables":{}}}
```

fix: examples -> forum -> current_user function -> fix error invalid input syntax for integer: ""

---

src/interfaces.ts
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

Fixes #753 
Removes `absoluteRoutes` which was never officially released. This setting will now throw an error, to let people know we've found a better way.
Auto-sniffs if we're being mounted in Node at a subpath, e.g. using express, so doesn't need the user to do anything in that case.
Typically useful if you run PostGraphile behind a proxy that changes the external URL.

feat(http): add externalUrlBase setting

---

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

GraphiQL is not recommended in production.

feat(graphiql): add basic protection against clickjacking

---

package.json
src/interfaces.ts
src/postgraphile/__tests__/postgraphileIntegrationQueries-test.js
src/postgraphile/extendedFormatError.ts
src/postgraphile/http/__tests__/__snapshots__/createPostGraphileHttpRequestHandler-test.js.snap
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
yarn.lock

Updates PostGraphile to respect the latest GraphQL spec, using the `exceptions` property on errors:
https://facebook.github.io/graphql/draft/#sec-Errors
Note: we've kept all the old properties for backwards compatibility but these will be removed in version 5 so we strongly recommend you switch to using the new error.extensions.exception object rather than using error directly.
Fixes #896

fix(graphql): respect GraphQL working draft changes to errors

---

package.json
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
yarn.lock

Fastify passes our core test suite 💯 `fastify.use(postgraphile(...))`
It doesn't seem to work with mounting a middleware on a subpath right now (i.e. `fastify.use('/path/to', postgraphile(...))`), presumably it's not doing `originalUrl` / `url` manipulation?
Fixes #869

feat(http): add tests for fastify server

---

src/postgraphile/__tests__/postgraphile-test.js
src/postgraphile/postgraphile.ts

Fixes #951 
**Note:** I had to manually run `yarn add graphql postgraphile-core` in order to get the tests running on my local machine. For whatever reason these dependencies were not installed with just `yarn`.

fix(server): throw when encountering `undefined` positional arguments

---

src/postgraphile/withPostGraphileContext.ts

Previously a call to `pgPool.query` (in the user's code) would throw an error when some `DEBUG` variables were set:
```
/usr/src/app/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:250
promiseResult.catch((error) => {
^
TypeError: Cannot read property 'catch' of undefined
at Client.pgClient.query (/usr/src/app/node_modules/postgraphile/build/postgraphile/withPostGraphileContext.js:250:31)
at PendingItem.connect [as callback] (/usr/src/app/node_modules/pg-pool/index.js:294:14)
at Pool._pulseQueue (/usr/src/app/node_modules/pg-pool/index.js:142:21)
at process.nextTick (/usr/src/app/node_modules/pg-pool/index.js:178:37)
at _combinedTickCallback (internal/process/next_tick.js:132:7)
at process._tickDomainCallback (internal/process/next_tick.js:219:9)
error Command …
```

fix(debug): be more careful when monkey-patching

---

package.json
postgraphiql/package.json
postgraphiql/src/components/PostGraphiQL.js
postgraphiql/src/components/postgraphiql.css
postgraphiql/yarn.lock
src/interfaces.ts
src/postgraphile/cli.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/setupServerSentEvents.ts
src/postgraphile/http/subscriptions.ts
src/postgraphile/pluginHook.ts
src/postgraphile/withPostGraphileContext.ts
yarn.lock

Enables people to experiment with their own subscription implementations without needing to use an alternative server.

feat(server): websockets support

---

src/postgraphile/postgraphile.ts

This is a bug that occurs when you plug in a pg.Pool into the postgraphile middleware while using webpack's uglify. The "quacksLikePgPool" check fails in 2 places and the postgraphile middleware never runs.
First, ```(pgConfig instanceof Pool)``` at https://github.com/graphile/postgraphile/blob/577c1e6df08ebe47e8880665ce99580cf7d375a7/src/postgraphile/postgraphile.ts#L223 is always false, as far as I can tell. Right now the passing comparison would be ```(pgConfig instanceof Pool.super_)```. I included both checks for the sake of future-proofing when node-postgres decides to change how it handles subclasses. https://github.com/brianc/node-postgres/issues/1612 and https://github.com/brianc/node-postgres/pull/1541
Second, the check `(constructorName(pgConfig) !== 'Pool' && …

fix(postgraphile): check pgConfig constructor's function, not its name

---

.prettierignore
package.json
sponsors.json
src/interfaces.ts
src/postgraphile/__tests__/__snapshots__/postgraphileIntegrationMutations-test.js.snap
src/postgraphile/cli.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/index.ts
src/postgraphile/pluginHook.ts
src/postgraphile/postgraphile.ts
src/postgraphile/withPostGraphileContext.ts
tslint.json
yarn.lock

- Adds websockets support to PostGraphile and PostGraphiQL
- `--subscriptions` implies `--enhance-graphiql`
- `--live` implies `--subscriptions`
- Add `ownerConnectionString` option which can be used to install the watch fixtures, among other things
- Improve error messages
- Output less debugging information in error messages when PostgreSQL server restarts
- Tweak typings of pluginHooks
- Stronger types in other places

feat(graphql): subscriptions and live queries enhancements

---

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

Spotted this bug in the timing logs; have simplified to use `toFixed` instead (also guaranteeing no rounding issues!)
Introduced in https://github.com/graphile/postgraphile/commit/79b6846ca97e8d2adf398540e9a6bc05e7d84b2b

fix(logs): fix timing information

---

src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

Added `Access-Control-Expose-Headers` header to allow user agents access to the `X-GraphQL-Event-Stream` header.

Added Access-Control-Expose-Headers for X-GraphQL-Event-Stream header

---

package.json
src/postgraphile/http/__tests__/__snapshots__/createPostGraphileHttpRequestHandler-test.js.snap
src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js
src/postgraphile/http/__tests__/supertest/index.ts
src/postgraphile/http/__tests__/supertest/lib/agent.ts
src/postgraphile/http/__tests__/supertest/lib/test.ts
src/postgraphile/http/setupServerSentEvents.ts
src/postgraphile/postgraphile.ts
yarn.lock

Fixes #994 
This PR that took me many hours:
- disables one line of code when in HTTP2 mode (namely: `res.setHeader('Connection', 'keep-alive');`)
- includes a fork of supertest that sort-of supports superagent v4 which supports http2
- hopefully doesn't introduce any bugs into the tests
- was a pain in the butt.

feat(http2): basic HTTP2 support for event-stream

---

prettier.config.js
src/postgraphile/__tests__/withPostGraphileContext-test.js
src/postgraphile/withPostGraphileContext.ts

Currently it is only accepted to provide type `string` for JWT secret when JWT can accept both `buffer` and `string`. With this PR, we allow type buffer to be passed as jwtSecret.

fix(postgraphile): add buffer support as jwt secret

---

examples/forum/TUTORIAL.md
examples/forum/schema.sql
examples/forum/scripts/build-schema

This is a pretty small set of changes.
1. Simplified the `authenticate` function in the schema so that it is simple sql code that requires less explanation.
1. Added a `change_password` functionality.
1. Added Windows support to the build_schema (just needed to add `trim` thanks to windows newline nonsense)

Improvements to Forum Example Authentication and Windows Support for Build Schema Script

---

src/interfaces.ts

The WithPostGraphileContextOptions interface does not require this property and sets a default if it needs one.

making the jwtRole optional, fixes #1028

---

src/interfaces.ts
src/postgraphile/__tests__/__snapshots__/postgraphileIntegrationSchemaExport-test.js.snap
src/postgraphile/__tests__/postgraphileIntegrationSchemaExport-test.js
src/postgraphile/cli.ts
src/postgraphile/schema/exportPostGraphileSchema.ts

Fixes #1039 
Adds `--sort-export` CLI flag / `sortExport: true` library option.

feat(export): option to lexicographically sort exported schema

---

src/interfaces.ts
src/postgraphile/cli.ts
src/postgraphile/postgraphile.ts

Relates to #1044
Prevents this new feature being a breaking change.
To _not_ exit on fail you need to set either `--retry-on-init-fail` on the CLI or `retryOnInitFail: true` in the library.

feat(server): option to not exit when initial schema build fails

---

src/postgraphile/http/subscriptions.ts

https://github.com/graphile/postgraphile/blob/44c44e2196883b7d659ff796e1eac8c4557e0884/src/postgraphile/http/subscriptions.ts#L155
Subscriptions do not work correctly when mounted on a subpath. This pull request resolves this for most use cases by using the value of the existing `externalUrlBase` option to determine whether we should account for a specific subpath in the web socket handler.
The documentation already tells users to fill out when mounting Postgraphile at a subpath, so no additional changes are required by users wanting to take advantage of this fix.
When this option is not specified we default to a empty string which results in the same behaviour as before.

fix(postgraphile): use externalUrlBase for websockets

---

package.json
yarn.lock

Hotfix; fixes issue where `makeExtendSchemaPlugin` disables the built-in directives `@skip` and `@include`

fix(deps): upgrade postgraphile-core

---

postgraphiql/src/components/PostGraphiQL.js

It was pretty annoying to me that PostGraphiQL "forgets" the headers at every page refresh (we have schema polling disabled).
This will store the headers in localStorage as soon as they're valid JSON and retrieve them on component creation.

feat(postgraphiql): save headers to localStorage

---

src/postgraphile/cli.ts
yarn.lock

Fixes #1092  
Fixes #881
If this breaks your application then it's because some of your CLI arguments were being ignored. This could potentially be very dangerous; as such I'm calling this a bugfix rather than a breaking change. I don't believe there's any projects legitimately relying on this broken behaviour. If you need to add CLI arguments for a plugin or similar the way to achieve this is with a [server plugin](https://www.graphile.org/postgraphile/plugins/).
If you're affected by this (CLI only) you'll notice because the server will immediately exit with a failing status code (currently `1` but don't rely on that).

fix(cli): abort if given unused arguments

---

src/interfaces.ts
src/postgraphile/http/subscriptions.ts

So it can be used with Express middleware, not just HTTP.
Also fixed a bunch of lint warnings whilst I was at it.

chore(types): make Middleware a generic type

---

postgraphiql/src/components/PostGraphiQL.js
postgraphiql/src/components/postgraphiql.css

Also improves some wording, styles, and adds a link out to EXPLAIN.

fix(graphiql): solve vertical scrolling issue

---

postgraphiql/src/components/PostGraphiQL.js

in isSubscription not all operations always run, so
if there is provided name of operation, check only that operation type.

fix(graphiql): fix operation detection on multi-op documents

---

package.json
src/index.ts
src/interfaces.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/liveSubscribe.ts
src/postgraphile/http/subscriptions.ts
src/postgraphile/pluginHook.ts
src/postgraphile/withPostGraphileContext.ts
yarn.lock

The long planned migration to TypeScript is now complete! Code churn has been absolutely massive, but all the tests still pass and none of the APIs have changed in any significant way.
- https://github.com/graphile/graphile-engine/pull/573
- https://github.com/graphile/graphile-engine/pull/578
- https://github.com/graphile/graphile-engine/pull/579
- https://github.com/graphile/graphile-engine/pull/581
TypeScript users may have to update types in places, particularly if they have their own custom Graphile Engine plugins written in TypeScript.
Anyone using `additionalGraphQLContextFromRequest` may need to use "declaration merging" to allow them to add additional fields to the context that they can then use later:
```ts
declare module 'postgraphile' {
interface GraphileResolverContext { …
```

feat(types): much stronger TypeScript types

---

src/postgraphile/cli.ts

I'm working on using Postgraphile on a cloud hosting service in a customized Docker image.  Being able to pass the `jwtSecret` via environment variables would make configuring different environments a lot easier.
Passing the info via command line arguments makes it harder to reuse one docker image with different settings.
I haven't studied the codebase in depth, I hope that the place I chose is a reasonable place to look for the environment variable.

feat(jwt): add support for JWT_SECRET envvar

---

src/interfaces.ts

As per: [graphile/graphile-engine#479](https://github.com/graphile/graphile-engine/pull/479)
Clarifies: [graphile/postgraphile-lambda-example#16](https://github.com/graphile/postgraphile-lambda-example/issues/16)

docs: `readCache` takes an object too

---

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

fix(http): don't use LRU when queryCacheMaxSize too small

---

src/interfaces.ts

Looks like this has been supported for a while but went undocumented.

fix(ts): add jwtSignOptions to PostGraphileOptions type

---

src/interfaces.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/postgraphile.ts

Previously, if a fatal error occurred that prevented building the GraphQL schema:
- if `retryOnInitFail` was not set/falsy, the process would exit with code 34
- if `retryOnInitFail` was truthy, PostGraphile would keep retrying forever, with exponential backoff
Fatal errors can include things like not being able to connect to the database, and not being able to build the schema due to a naming conflict. These issues could be solved (e.g. when the database comes online, or if someone adds a smart comment to the database) so for some users this made sense. For others, particularly those running multiple versions of PostGraphile through the same node process, it made less sense.
This PR gives users a third option; they may specify `retryOnInitFail` as a callback function. The function is …

feat: allow overriding init fail handling

---

package.json
yarn.lock

* **perf:** overhaul postgres interval code ([graphile/graphile-engine#679](https://github.com/graphile/graphile-engine/issues/679)) ([graphile/graphile-engine#683](https://github.com/graphile/graphile-engine/issues/683)) (upstreamed in [bendrucker/postgres-interval#34](https://github.com/bendrucker/postgres-interval/pull/34))
* **tags:** fix non-null for multiple [@unique](https://github.com/unique) tags ([graphile/graphile-engine#681](https://github.com/graphile/graphile-engine/issues/681)) ([0747562](https://github.com/graphile/graphile-engine/commit/07475622372a42e1f2105abb50a8a4d8ceb0ba61))
* **types:** fix enum tables when used in custom mutations ([graphile/graphile-engine#680](https://github.com/graphile/graphile-engine/issues/680)) …

fix: upgrade postgraphile-core

---

examples/servers/fastify3/rum-and-raisin.ts
src/postgraphile/http/frameworks.ts

This prevents compression on the event stream route when using Fastify v3 server with the `fastify-compress` plugin. User code no longer needs to worry about this. It's a bit of a hack to mutate the client headers, but it seems to be the only way we can handle it internally; however I've sent an upstream fix that will hopefully prevent Fastify attempting to compress event streams: https://github.com/fastify/fastify-compress/pull/133
Negligible.
Overwrites client header; but otherwise negligible.

fix: don't compress event stream in Fastify

---

src/postgraphile/http/frameworks.ts
src/postgraphile/http/setupServerSentEvents.ts

Makes it more obvious what it does, and that `end` and `endWithStream` are mutually exclusive.
This is a public interface, but it's not been officially released yet, so this is not a breaking change.
None
None

chore: rename responseStream to endWithStream

---

examples/servers/fastify3/rum-and-raisin.ts
package.json
src/postgraphile/http/frameworks.ts
yarn.lock

For `pgSettings` and `additionalGraphQLContextFromRequest` users may need a way to get "back" from the Node request to the Fastify request so that they can use the features of Fastify middleware. We already enable this via `req._koaCtx` for Koa, this PR adds `req._fastifyRequest` for Fastify (v3).
Fixes #1382
Negligible
None known.

feat: allow access to Fastify request from Node request

---

postgraphiql/package.json
postgraphiql/src/components/PostGraphiQL.js
postgraphiql/src/index.css
postgraphiql/yarn.lock

This is long overdue. Upgrade GraphiQL from 0.13.2 to 1.0.6; upgrade GraphiQL Explorer from 0.4.6 to 0.6.2.
- Headers are [now handled natively by GraphiQL](https://github.com/graphql/graphiql/pull/1543) (next to the variables editor) - much nicer UI than ours was
- New merge button ([fixed in GraphiQL](https://github.com/graphql/graphiql/pull/1542) by yours truly way back in May)
- New "copy" button
- Fixes various layout issues
Fixes #1375
Unknown.
None known.
- Check it works with all the frameworks:

feat: upgrade GraphiQL/GraphiQL Explorer

---

postgraphiql/src/components/PostGraphiQL.js
src/interfaces.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

(Maintainer note: accidentally closed #1386 by merging another PR; then couldn't rebase #1387, so opened this one. Author is @eddiewang)
This PR adds the ability to set the Request credential behavior on the GraphiQL instance built into Postgraphile. This allows users that rely on cookies to have a seamless experience querying in GraphiQL.
- Negligible, adds an extra option in the config.
- Should only be enabled in dev-mode / unknown

feat(graphiql): add configurable credentials behavior

---

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/frameworks.ts
src/postgraphile/pluginHook.ts

With the middleware we have `postgraphile:http:handler` hook that allows exiting the middleware early, or manipulating the request in some way. This PR adds as similar hook to each of the route handlers (event stream, favicon, graphiql, graphql) so you can do the same within the specific route handler - note that these also work from the middleware too, so may be the preferred way of accomplishing some tasks.
Fixes #1383 
Minimal.
None known.

feat: hooks for route handlers

---

package.json
src/interfaces.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/frameworks.ts
yarn.lock

TypeScript baulks when it sees us importing types from `koa` and `fastify` without adding these things to dependencies; however we don't depend on these things and don't want our users to have to install them if they're not using them (if they use express, no need; if they use koa there's no need for the fastify types and vice versa). It seems that the best way to deal with this (according to Daniel Rosenwasser, the TypeScript Program Manager at Microsoft) currently is to use stub types that are structurally compatible with the underlying types: https://twitter.com/drosenwasser/status/1326294777969532928. This PR does that.
None - types only.
None - types only.

fix(types): replace explicit framework types with stubs

---

postgraphiql/yarn.lock
yarn.lock

(Only affects yarn.lock, so no change for library consumers.)

chore(deps): upgrade some dependencies

---

examples/servers/common.ts
examples/servers/schema.graphql

Added an export of the GraphQL schema from the examples to make it easier to spot if anything goes wrong (currently all schema export identical schemas, which is desired).

chore(examples): export GraphQL schema

---

examples/servers/fastify3/rum-and-raisin.ts
examples/servers/fastify3/vanilla.ts

Caused by #1391. Very sad that you have to cast `req._fastifyRequest as FastifyRequest` but I don't know how to get around that.
None
None

chore(examples): fix types

---

src/postgraphile/cli.ts

Adds "Node.js version" section to PostGraphile CLI output (includes platform). Also hopefully draws more attention to the `--enhance-graphiql` recommendation as I've seen a lot of people wanting this option but not noticing the previous message.
Fixes #1400.
Negligible.
None known.

feat: add Node version info and clarify enhance-graphiql

---

src/interfaces.ts

A little documentation update that explain jwtPublicKey, in usage-library.md.
I needed it but couldn't find it in the docs, hope it will help others 😄.

docs(options): add explanation for jwtPublicKey

---

Dockerfile

Dockerfile references Node 12; GRAPHILE_TURBO now requires Node 14
The Docker Hub image will run slower; npm build is unaffected.
None.

fix(docker): remove GRAPHILE_TURBO

---

src/interfaces.ts
src/postgraphile/cli.ts
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
src/postgraphile/http/subscriptions.ts

Fixes #1416.
Small oversight in `cli.ts`; also increased safety of `enhanceHttpServerWithWebSockets` so the API doesn't have a breaking change.
Negligible.
None known.

fix(ws): fix missing websockets config on CLI

---

.eslintrc.js
isTurbo.js

`GRAPHILE_TURBO` is an opt-in to performance optimisations from reduced transpilation; it always targets the latest Node release. Currently we need support for optional chaining `?.` syntax which requires Node 14.
None.
If you upgrade PostGraphile whilst running Node 12 AND with the opt-in `GRAPHILE_TURBO` flag enabled then your server may refuse to start. It's advised that you only use `GRAPHILE_TURBO` when you are targetting the very latest Node.js release and you want the absolute best performance we can squeeze out; for stable usage, do not use this flag.

fix(turbo): warn users that Node v14 is required

---

package.json
yarn.lock

* **graphql:** ensure buildSchema fails on invalid GraphQL schema ([#695](https://github.com/graphile/graphile-engine/issues/695)) ([c837e09](https://github.com/graphile/graphile-engine/commit/c837e0968e8e98f1461cec47e4e48ede020a766c))
* **pg-sql2:** use same placeholder for same sql.value node ([#705](https://github.com/graphile/graphile-engine/issues/705)) ([969d923](https://github.com/graphile/graphile-engine/commit/969d92313f5e86e7a115726bedc197795a63b97c))
* **enum:** enum views ([#704](https://github.com/graphile/graphile-engine/issues/704)) ([d2770a5](https://github.com/graphile/graphile-engine/commit/d2770a5e847b9839e0ac3bd2848817fd2d53bcfb))
* **utils:** makeExtendSchemaPlugin interfaces support ([#696](https://github.com/graphile/graphile-engine/issues/696)) …

chore(deps): upgrade Graphile Engine

---

package.json
yarn.lock

Fixes pool exhaustion bug with `--watch` mode.
Negligible.
Fixes potential denial of service in watch mode (watch mode is not recommended for production).

fix(deps): upgrade Graphile Engine

---

src/postgraphile/withPostGraphileContext.ts

We were handling a rejection after a delay, that causes Node v15+ to exit (and is super noisy in Node 14); this fixes it.
Negligible.
None known.

fix(explain): fix 'unhandled' promise rejection

---

src/postgraphile/http/liveSubscribe.ts
src/postgraphile/pluginHook.ts

Based on https://github.com/graphile/postgraphile/compare/main...Venryx:main and enabled by #1482  this adds a new pluginHook that can be used to augment results from the `liveSubscribe` method, for example to implement JSON patch transform.
Very slight overhead added to every liveSubscribe execution.
None known.

feat(hooks): add postgraphile:liveSubscribe:executionResult hook

---

src/postgraphile/cli.ts

`pg-connection-string` now returns the `port` as a `string` (which differs from previous versions where it was a number). This code now handles both strings and numbers.
Fixes #1494 
Negligible; startup only, CLI only.
None known.

fix(cli): fix parsing port number

---

src/postgraphile/cli.ts

Addresses the CLI side of https://github.com/graphile/postgraphile/issues/1455
None
None

fix(cli): handling of SSL options from the connection string

---

scripts/make-assets
scripts/proxied-test-server.js
src/postgraphile/http/createPostGraphileHttpRequestHandler.ts

[String.prototype.substr()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) is deprecated so we replace it with [String.prototype.slice()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/slice) which works similarily but isn't deprecated.
.substr() probably isn't going away anytime soon but the change is trivial so it doesn't hurt to do it.
From past experience there is no performance impact due to switching to slice()
None as the returned values are still the same

chore: replace deprecated String.prototype.substr()

---

src/postgraphile/http/subscriptions.ts

_*Speaking on behalf of `graphql-ws`, not sure if this happens with the deprecated `subscriptions-transport-ws`. Whatever the case is, the fix includes **both** libraries._
A server can close the socket at any time, even when a GQL operation is being prepared but not yet executed.
If the socket is closed while preparing, neither [`onError`](https://github.com/graphile/postgraphile/blob/b59c246b378dc72f8c90b27e633bf421c4fa3e0b/src/postgraphile/http/subscriptions.ts#L437-L442) nor [`onComplete`](https://github.com/graphile/postgraphile/blob/b59c246b378dc72f8c90b27e633bf421c4fa3e0b/src/postgraphile/http/subscriptions.ts#L451-L453) will be called simply because the operation was never executed. This causes a rather critical bug of not releasing PostGraphile contexts for the affected socket, …

fix(ws): release all socket's contexts on close

---

src/postgraphile/http/subscriptions.ts

Follow up to #1612
Infinitesimal improvement.
For long running PostGraphile servers that handle websockets this prevents the `keepalivePromisesByContextKey` growing unbounded. It'd take a long time to exploit this, but it is an improvement.

chore: minor refactoring of websocket code

---

src/postgraphile/http/subscriptions.ts

[`graphql.validate`](https://github.com/graphql/graphql-js/blob/b38429f4d46b17f23d15406a2ca0d1eb201864b6/src/validation/validate.ts#L38-L46) will throw if its typings are not respected.
This PR adds pre-validation steps making sure the operation document, as well as the operation AST, is available.
Note that we don't do the same for the schema - not having it is a fatal error still.
None.
None.

refactor(ws): make sure operation is available before validating

---

README.md

Add a note to the README indicating that Mac users should use a different port.
Relates to #1551

docs(README): note macOS AirPlay port 5000 conflict

---

.github/workflows/ci.yml

CI seems to be failing on Node 8.x and PG 9.6, 10 and 11 due to dependency shifts in Docker and other such CI-only things. Fixing these things is non-trivial (e.g. we'd have to roll our own Docker images) and I can't justify the expenditure of effort there when I want to focus on getting V5 ready to use, so I'm just removing these legacy versions from CI. We'll need to be careful/strict in future PRs to ensure we don't merge anything that would break on PG 9.6 or Node 8.x - but we're not anticipating merging anything major into PostGraphile V4 anyway, so this shouldn't be a big deal.

chore(ci): remove Postgres <12 and Node <10 from CI

---

.github/workflows/docker-hub.yaml

Newer Mac computers with their M1 chips use the ARM architecture [1]. Currently there is no docker image for postgraphile published to Docker Hub supporting the `arm64` platform, only for `amd64`. This commit adds compilation for an ARM image as well, so that developers on newer Mac computers can use postgraphile inside a container as well.
[1] https://en.wikipedia.org/wiki/Apple_M1
The build time will be longer. Especially cross-platform compilation for ARM will take longer than AMD compilation on AMD ci workers due to necessary QEMU virtualization.
none
As this is a CI change, I don't think any of the checklist items apply. Please correct me if I'm wrong.
I chose `fix` as the type, as it does not really add a new feature to postgraphile but adds a missing platform for Mac.

feat(ci): build arm64

---

.github/workflows/ci.yml
Dockerfile

The issue is with Node 12 being so old I had TLS connection issues that would hang after startup and silently use all available memory. The node 12 image is using alpine3.15 anyway so this PR keeps alpine the same. While changing versions just moved any reference to node to the current LTS.
Would expect an improvement.
Published docker images would be using a supported version of Node.
Potentially could remove node 8, 10 and 12 from the matrix as they go out of support.
All I've tested is manually installing node 17 within the existing container and things seemed to work fine. Hopefully the CI tests can rundown any issues.

chore: update to Node 16 LTS in CI & published docker images

---

graphile-build/graphile-build-pg/src/plugins/PgFakeConstraintsPlugin.ts
postgraphile/postgraphile/__tests__/schema/v4/foreignKey-smart-tag-bad.test.ts

pgFakeConstraintsAutofixForeignKeyUniqueness is mispelled as pgFaceConstraintsAutofixForeignKeyUniqueness
None
None

fix misspell in help

---

.changeset/violet-adults-confess.md
graphile-build/graphile-build-pg/src/plugins/PgBasicsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgCodecsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgEnumTablesPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgProceduresPlugin.ts
postgraphile/postgraphile/__tests__/helpers.ts
postgraphile/postgraphile/__tests__/mutations/v4/partitions.unqualified.json5
postgraphile/postgraphile/__tests__/mutations/v4/partitions.unqualified.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/partitions.unqualified.sql
postgraphile/postgraphile/__tests__/mutations/v4/partitions.unqualified.test.graphql
utils/pg-sql2/src/index.ts

Fixes https://github.com/graphile/crystal/issues/191
Needs tests and documentation before this becomes an "officially supported" interface. GET INVOLVED!
Add `preset.gather.pgIdentifiers` setting (values: 'qualified' or 'unqualified'); if set to 'unqualified' then we will not add the schema name to table or function identifiers - it's up to you to ensure they're present in the `search_path` (which you can set via `pgSettings` on a per-request basis).

Add 'pgIdentifiers' setting to allow _not_ fully qualifying table/function names

---

.changeset/honest-birds-pull.md
grafast/dataplan-json/tsconfig.json
grafast/dataplan-pg/tsconfig.json
grafast/grafast/tsconfig.json

Should have been enabled once we launched the beta; oops.

Enable source maps

---

.changeset/itchy-ties-kick.md
grafast/grafast/src/engine/executeBucket.ts

Fixes #1766
Unexplored; likely there is an execution cost in any queries with polymorphism and/or side effect steps. The amount of impact is likely to be small, but nonetheless we should look into it at some point.
None known.

Only honour side-effect errors relating to current polymorphic path

---

postgraphile/website/postgraphile/connections.md

The field to use in the preset file for configuring list behaviour is `defaultBehavior` instead of `globalBehavior`,
as described here https://postgraphile.org/postgraphile/next/behavior#global-default-behavior
None 
None

Fix docs for configuring list behavior in preset

---

src/interfaces.ts
src/postgraphile/cli.ts

This adds the ability to set `usePartitionedParent` from https://github.com/graphile/graphile-engine/pull/801
It depends on that PR being merged.
None
None

feat(interface): add usePartitionedParent (#1160)

---

.changeset/fresh-hats-knock.md
grafast/ruru-components/src/interfaces.ts
grafast/ruru-components/src/ruru.tsx
postgraphile/postgraphile/graphile.config.ts

Fixes https://github.com/graphile/crystal/issues/1794
Example plugin:
```ts
const RuruQueryParamsPlugin: GraphileConfig.Plugin = {
name: "RuruQueryParamsPlugin",
version: "0.0.0",
grafserv: {
hooks: {
ruruHTMLParts(_info, parts, extra) {
parts.headerScripts += `
<script>
const currentUrl = new URL(document.URL);
const query = currentUrl.searchParams.get("query");
const variables = currentUrl.searchParams.get("variables");
if (query) {
RURU_CONFIG.initialQuery = query;
RURU_CONFIG.initialVariables = variables;
}
</script>
`;
},
},
},
};
```

Enable a Ruru plugin to populate query and variables from query string

---

.changeset/healthy-kiwis-notice.md
grafast/ruru-components/src/interfaces.ts
grafast/ruru-components/src/ruru.tsx
postgraphile/postgraphile/graphile.config.ts

Fixes [#1798](https://github.com/graphile/crystal/issues/1798)
Adds `onEditQuery` and `onEditVariables` props to the ruru config that are passed through
to the underlying `GraphiQLInterface`. 
Adds a plugin that updates the URL `query` and `variables` query params on edits.
Also deprecates the `initialQuery` and `initialVariables` props in favor of `query` and `variables`.

Add passthrough `onEdit` callbacks to the Ruru config with a plugin to update URL query params

---

postgraphile/website/postgraphile/crud-mutations.md

With example, get the error "Error: 'create' behavior is forbidden; did you mean 'insert'?" Using insert worked.
documentation
none

Fix 'create' to 'insert' in behavior example

---

postgraphile/website/postgraphile/make-extend-schema-plugin.md

Added a new info section to explain that the table types are automatically created while introspection of the database. It provides a link to https://postgraphile.org/postgraphile/next/tables for further reading.
It enhances the documentation with relevant link to the section for further reading.
No performance impact
No security impact

Add note to `makeExtendSchemaPlugin` docs indicating where `Channel` type originated

---

.changeset/red-coins-impress.md
graphile-build/graphile-build-pg/src/plugins/PgIntrospectionPlugin.ts

Fixes #1761
There was two bugs in the introspection plugin:
1. the cache was being invalidated too early, which meant that multiple database events in quick succession would incorrectly reuse previous caches
2. the cache _also_ cached the "announcements" of introspection, meaning when the cache is used the schema building wouldn't even see the database changes!
I've refactored the code to separate the side effects from the introspection so that they can be cached separately (side effects to state, introspection to permanent cache) and I've now tracked whether the introspection results are "dirty" or not - if another event arrives before introspection of the DB occurs then we'll mark the introspection as dirty to ensure that it isn't reused.
None known.
None known.

Fix schema emptying issue from watch mode

---

.changeset/seven-experts-grow.md
graphile-build/graphile-build-pg/__tests__/utils.test.ts
graphile-build/graphile-build-pg/package.json
graphile-build/graphile-build-pg/src/utils.ts

Fixes #1836; see that issue for details.
This is technically a breaking change, but I very very much doubt anyone would be impacted negatively by it.
Marginal additional cost when parsing smart tags.
None known.

Make smart tags parser track parenthesis to allow for spaces

---

.changeset/rude-wombats-decide.md
grafast/grafserv/package.json
grafast/grafserv/src/servers/fastify/v4/index.ts
yarn.lock

Fastify integration had broken support for websockets.
This morning, we discussed the issue on Discord: https://discord.com/channels/489127045289476126/953710447087980654/1170996540639281214
unknown
unknown

wsHandlers are only allowed if method: "GET"

---

postgraphile/website/src/pages/index.js

Truly the smallest documentation change. I noticed that PostgreSQL had an extra "s" when I took a look at the documentation site today.
None
None

Fix spelling of PostgreSQL

---

.changeset/hip-ants-flash.md
postgraphile/postgraphile/src/cli.ts

CLI flags override the config; so if you have `watch: false` in the config but run the CLI with `postgraphile --watch` then watch mode should be enabled. However because we had `default: false` in the config for the argument parser, we were overriding `watch: true` in the config with `watch: false` from the CLI.
Removing this default resolves the issue.
Issue raised by @TimoStolz via Discord: (sponsors only channel): https://discord.com/channels/489127045289476126/953710447087980654/1176875333560062145
None.
None.

Fix bug in postgraphile CLI parser for no `--watch`

---

.changeset/fifty-donkeys-sort.md
grafast/grafast/__tests__/errorHandlingStreamTermination-test.ts
grafast/grafast/__tests__/loadOne-test.ts
grafast/grafast/src/interfaces.ts
grafast/grafast/src/steps/load.ts
grafast/website/grafast/step-library/standard-steps/access.md

Follow-up to #1868; a quick scan of the source had me scratching my head and it turns out there was a bug hiding there - we never used the values of an ioEquivalence object, just assumed that keys and values were the same! This is now fixed.
Negligible.
Fixes a bug.

Fix loadOne/loadMany ioEquivalence for object specs

---

.changeset/two-panthers-laugh.md
grafast/dataplan-pg/src/interfaces.ts
graphile-build/graphile-build-pg/src/plugins/PgRefsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts
postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql
postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql
postgraphile/website/postgraphile/refs.md

Specify `from` in `@ref` to apply refs to a single type

---

.changeset/khaki-fans-kiss.md
.changeset/swift-cows-beam.md
grafast/dataplan-pg/src/steps/pgUnionAll.ts
grafast/website/docusaurus.config.js
graphile-build/graphile-build-pg/src/plugins/PgInterfaceModeUnionAllRowsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgPolymorphismOnlyArgumentPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgPolymorphismPlugin.ts
graphile-build/graphile-build-pg/src/preset.ts
graphile-build/graphile-build/src/makeNewBuild.ts
postgraphile/postgraphile/__tests__/queries/polymorphic/only.json5
postgraphile/postgraphile/__tests__/queries/polymorphic/only.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/only.sql
postgraphile/postgraphile/__tests__/queries/polymorphic/only.test.graphql
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.app-condition.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.app-order.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.app-page-2.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.app-totalCount.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.app-vuln-totalCount.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/person-app-vulns.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/vulns.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/vulns.union_owners.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/vulns.union_owners.simple.mermaid
postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql
postgraphile/website/docusaurus.config.js

Adds an `only` argument (an enum list) to _some_ polymorphic relation fields (currently only those for lists/connections of "mode=union" interfaces). When present, only the given types will be included in the result. 
Currently this is enabled by default but marked as experimental. Due to #1816 Ruru won't recognize the argument exists, but it's there so just write it and ignore the red squigglies. The enum values are the exact names of the types.
Example query:
```graphql
{
allApplications(only: [GcpApplication, AwsApplication]) {
nodes {
__typename
... on AwsApplication {
awsId
}
... on GcpApplication {
gcpId
}
vulnerabilities(only: [ThirdPartyVulnerability]) {
nodes {
__typename
id
name
... on FirstPartyVulnerability {
teamName
}
... on ThirdPartyVulnerability {
vendorName
}
}
}
}
}
} …
```

Enable limiting polymorphic relations to only certain types

---

.changeset/giant-cobras-smell.md
.changeset/mighty-flies-do.md
.changeset/sweet-books-tie.md
grafast/dataplan-pg/src/codecs.ts
graphile-build/graphile-build-pg/src/plugins/PgCodecsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgProceduresPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgTablesPlugin.ts
postgraphile/postgraphile/graphile.config.ts
postgraphile/postgraphile/src/plugins/PgV4InflectionPlugin.ts

Codec naming conflicts were happening when you had multiple pgServices due to a bug in the `_schemaPrefix` inflector (fixed) and duplicate names being generated for array codecs (fixed). Also, the process was exiting when it hit specific bugs in watch mode; this turned out to be a missing `await`... Also fixed.
Potentially breaking change since we're changing the names of things; but only impacts people who have set a name for their service and have set it to not `main` which you [should not do](https://github.com/graphile/crystal/pull/1881) unless you have more than one pgService.
Gather-phase, schema-phase, and watch mode only. No runtime impact.
Less crashy = more better-er?

List codec names; fix missing await

---

.changeset/nice-lobsters-add.md
graphile-build/graphile-build-pg/src/plugins/PgConnectionArgOrderByPlugin.ts

Fixes graphile/crystal-pre-merge#487 (probably... I didn't test it).
Negligible.
Negligible.

Fix orderBy:null regression

---

.changeset/fluffy-eagles-jam.md
grafast/grafast/src/engine/OperationPlan.ts
graphile-build/graphile-utils/src/makeWrapPlansPlugin.ts

Plan resolvers should return a step (or `null`); sometimes people forget the `return` statement and this can lead to misleading errors. Attempt to give a more sensible error up front.
Planning only.
None known.

Attempt to detect bad plan resolvers sooner

---

.changeset/curvy-vans-sleep.md
utils/graphile-config/__tests__/sorting-without-provider.test.ts
utils/graphile-config/src/sort.ts

Previously if there was no provider for a particular order constraint, then that order was ignored. It turns out there's no provider for `smart-tags`, but it has a lot of `before` and `after` constraints on it; all of which were ignored, which could result in plugins with `before: ["smart-tags"]` being loaded after plugins with `after: ["smart-tags"]`. Even though there's no provider for this, clearly this shouldn't be the case.
This PR solves the issue by creating a fake provider during the plugin sorting and then filtering it back out again at the end, enforcing that all `before: ["smart-tags"]` plugins are loaded before all `after: ["smart-tags"]` plugins.
Negligible startup cost.
None known, unless someone is playing silly buggers with plugin ordering... but plugins are trusted code …

Fix plugin ordering bug

---

postgraphile/website/README.md
postgraphile/website/postgraphile/config.mdx

Fixes issue #1873 
Adds a warning box about no need to set a name unless you have more than one pgService
Adds the lint:fix to the README
N/A
N/A
- ~[ ] I've added tests for the new feature, and `yarn test` passes.~
- ~[ ] I have detailed the new feature in the relevant documentation.~
- ~[ ] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).~
- ~[ ] If this is a breaking change I've explained why.~

website: pgServices Docs

---

.changeset/sour-lions-live.md
utils/pg-introspection/src/acl.ts
utils/pg-introspection/src/augmentIntrospection.ts

Looks like there was some older code hanging around which had faulty logic (in particular, it granted _NO PERMISSIONS_ to the owner of a table by default ?!); we already have a chain of logic that matches the Postgres source so we've deleted `aclsForTable` and used the shared logic instead.
I've also taken the time to make the code closer to the postgres source to make auditing easier.
Marginal, gather/build phase only.
Exposes more resources (because it's more correct).

Fix RBAC permission detection for tables

---

.changeset/tidy-grapes-cry.md
graphile-build/graphile-build/src/plugins/QueryPlugin.ts
postgraphile/postgraphile/graphile.config.ts

Loosen step assertion on Query type

---

.changeset/light-pandas-complain.md
.github/workflows/test-base.yml
utils/tamedevil/src/index.ts

Fixes #1897. Everything was already fine, but this helps prevent a regression.
None.
None.

Run tests with `--disable-proto=delete` (partly for Deno compatibility)

---

.changeset/metal-impalas-scream.md
grafast/grafserv/src/utils.ts

Fixes #1898
Negligible.
Improvement.

Only add stack traces to extensions if they're already present

---

.changeset/nasty-dragons-rush.md
grafast/grafast/src/makeGrafastSchema.ts
grafast/website/grafast/plan-resolvers.md
graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts
postgraphile/website/postgraphile/make-extend-schema-plugin.md

Relates to #1915 (but doesn't fix it).
Object types in Grafast can indicate that they must be represented by a particular step or set of steps; this can help to catch bugs early. For example, in PostGraphile a database table resource should be represented by a `pgSelectSingle` or similar class; representing it with `object({id: 1})` or similar would mean the step doesn't have the expected helper methods and downstream fields may fail to plan because their expectations are broken.
When writing a schema manually, you set this via `objectTypeConfig.extensions.grafast.assertStep` which can either be a step class itself (e.g. `objectTypeConfig.extensions = {grafast: {assertStep: PgSelectSingleStep}}`) or it can be an "assertion function" that throws an error if the passed step is not of the …

Add __assertStep support to makeGrafastSchema and makeExtendSchemaPlugin

---

grafast/grafserv/__tests__/errors.test.ts
grafast/grafserv/__tests__/exampleServer.ts
grafast/grafserv/src/middleware/graphql.ts

Currently, when you provide a function for the `grafast.context` option to populate context, and an error is thrown in the function (eg when parsing an auth header into context, but the auth header is malformed), execution bypasses the 'maskError' function, resulting in an 'Unknown error occurred' error in the response body, 500 status code, accompanied by a complete stack trace in the response.
https://discord.com/channels/489127045289476126/498852330754801666/1197168131756531732
I believe this fix also addresses the root cause of:
https://github.com/graphile/crystal/issues/1847
Unknown
_Should_ improve security by not disclosing stack trace information if errors are thrown in the context function.

Ensure response body contains expected error object when grafast context function throws an error

---

.changeset/tame-elephants-whisper.md
graphile-build/graphile-utils/__tests__/__snapshots__/makeExtendSchemaPlugin.test.ts.snap
graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts
graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts
postgraphile/website/postgraphile/make-extend-schema-plugin.md

Can now define field scope as part of plans:
```ts
const SGrovePlugin = makeExtendSchemaPlugin((build) => {
const { sql } = build;
const email = build.input.pgRegistry.pgResources.email;
return {
typeDefs: gql`
extend type Email {
threadAncestors: EmailsConnection
}
`,
plans: {
Email: {
threadAncestors: {
// 👇 👇 👇 👇 👇 👇 👇 👇 👇 👇
scope: {
isPgFieldConnection: true,
pgFieldResource: email,
},
// 👆 👆 👆 👆 👆 👆 👆 👆 👆 👆
plan($email) {
const $refs = $email.get("refs");
const $ancestors = email.find();
$ancestors.where(
sql`${
$ancestors.alias
}.id in (select unnest(${$ancestors.placeholder($refs)}))`,
);
return connection($ancestors);
},
},
},
},
};
});
```
This still averts the need for `embed()` used in V4.
Further, have made the system automatically guess the scope for connection types, so when …

makeExtendSchemaPlugin: add ability to define field scope as part of plans

---

.changeset/khaki-zoos-exercise.md
grafast/grafast/src/error.ts
grafast/grafast/src/index.ts

Related to https://github.com/graphile/crystal/issues/1921
Could not reproduce issue, so this is a guess.

Ensure SafeError and isSafeError are marked as exported for graphile-export

---

.changeset/friendly-meals-bow.md
.changeset/loud-carpets-pump.md
utils/pg-introspection/src/augmentIntrospection.ts
utils/pg-introspection/src/index.ts
utils/pg-introspection/src/introspection.ts

`pg_am` now added; so you can get the access method (e.g. `btree`) of an index:
```ts
const indexes = pgClass.getIndexes();
if (indexes.length > 0) {
const idx = indexes[0];
const indClass = idx.getIndexClass();
console.log(`Table ${pgClass.relname} index ${indClass?.relname}, method ${indClass?.getAccessMethod()?.amname}`);
}
```
- Fixes #1925 
Correctly excludes constraints on (or to) tables from extensions.
- Fixes #1750
Slightly more expensive introspection.
None known.

pg-introspection additions

---

.changeset/spicy-boats-learn.md
graphile-build/graphile-build-pg/src/plugins/PgTablesPlugin.ts
graphile-build/graphile-build/src/plugins/QueryPlugin.ts
utils/eslint-plugin-graphile-export/src/ExportMethods.ts
utils/eslint-plugin-graphile-export/src/index.ts

Added
* inputPlan
* applyPlan
to the list of exportable methods in eslint-plugin-graphile-export, applied lint:fix to the codebase, should Fix #1932 and allow proper export of a schema that has custom record types as function parameters

eslint-plugin-graphile-export, Add inputPlan,applyPlan as methods that can be generated as exportable - Fix #1932

---

.changeset/six-parents-collect.md
.changeset/spicy-boats-learn.md
postgraphile/postgraphile/graphile.config.ts
postgraphile/postgraphile/src/plugins/PgV4SimpleSubscriptionsPlugin.ts
utils/graphile-export/src/exportSchema.ts

- Fixes #1785 
When we're exporting functions, we now scan the function to ensure that it doesn't reference any variables outside of its scope. If it does, we'll abort the export with information about where the function was that failed, so that it can be wrapped in `EXPORTABLE()` (or have it's `EXPORTABLE` fixed).
:rotating_light: If your exports were previously invalid, they will now throw an error, preventing progress. This is safer, but it might break your existing `graphile-export` flows. We see this as a bugfix.
Makes `graphile-export` slower; but that's a one-time cost (per export...)
Improves security by reducing the chances of referencing unexpected globals.

graphile-export now detects invalid exports

---

postgraphile/website/postgraphile/smart-comments.md

I've been doing some digging into Postgraphile V5 and trying to build my own Plugin. While learning the codebase i decided to tackle a smaller issue i found with smart comment parsing. The following SQL:
```sql
COMMENT ON TABLE reports_public.report_base IS $$
@name ReportBase
@interface mode:relational type: report_type
@type Foo references: foo
@type Bar references: bar
$$;
```
Is currently parsed by the `parseSmartComment` as:
```json
{
"name": "ReportBase",
"description": "@interface mode:relational type: report_type\n@type Foo...."
}
```
The issue here is the `@interface` & `@type` tags being parsed as part of the description, rather than their own tags. This may be intentional, but i found it unintuitive and didn't realise that the extra `\n` i had placed between `@name` & …

Refactor smart comment parsing

---

.changeset/chatty-dodos-melt.md
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgSelectSingle.ts
grafast/grafast/src/step.ts
grafast/grafast/src/steps/__item.ts
grafast/grafast/src/steps/each.ts

`getDep` is an internal API for use within the class only; should other step classes need access to a step's dependencies they should do so via public APIs that the step exposes.
:rotating_light: If you were previously using `getDep` on a different class, you'll now need to use the public interfaces instead. There's a significant chance that what you were doing may not have been safe, and may have led to GraphQL spec non-compliance.
Fixes #1939
Negligible.
None known.

Mark getDep as protected to avoid abuse

---

grafast/website/grafserv/index.md

I've checked that this option works, it is already documented in the postgraphile documentation. This adds it to the grafserv documentation
- Fixes #1918
Documentation only
Documentation only

Add example of maxRequestLength

---

grafast/website/grafast/getting-started/index.mdx

Adds a section on TypeScript configuration under getting started in Grafast
- Fixes #1856
Documentation only
Documentation only

Add TypeScript config note to Grafast website

---

.changeset/flat-dingos-explain.md
grafast/dataplan-pg/src/examples/exampleSchema.ts
grafast/dataplan-pg/src/filters/pgBooleanFilter.ts
grafast/dataplan-pg/src/filters/pgClassFilter.ts
grafast/dataplan-pg/src/filters/pgOrFilter.ts
grafast/dataplan-pg/src/steps/pgCondition.ts
grafast/dataplan-pg/src/steps/pgInsertSingle.ts
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgSelectSingle.ts
grafast/dataplan-pg/src/steps/pgUpdateSingle.ts
graphile-build/graphile-build-pg/src/plugins/PgOrderByPrimaryKeyPlugin.ts
postgraphile/postgraphile/__tests__/kitchen-sink-data.sql
postgraphile/postgraphile/graphile.config.ts
utils/pg-sql2/src/index.ts

Writing `` sql`${$user.getClassStep().alias}.is_admin is true` `` is a chore; this change makes it so that `sql` can recognize embedded values that can be turned natively into SQL, for example `pgSelect` and `pgSelectSingle` can now be used like: `` sql`${$user}.is_admin is true` `` which is much simpler and easier to read.
Note: this is only useful for aliases, you cannot use this for placeholders.
Negligible, planning only.
I guess you could argue that it's slightly more magic, and thus slightly riskier that the coder might do the wrong thing? I can't see how this would turn into a vulnerability that would get past testing though.

Introduce concept of SQL-able to pg-sql2

---

.changeset/empty-numbers-act.md
utils/graphile-export/src/exportSchema.ts
utils/graphile-export/src/index.ts

We want people to be able to export the result of the gather phase, this adds that functionality (though it's far from optimal right now, for example the resulting file doesn't have good type safety for registry due to `Object.assign(Object.create(null), ...)`
Export only.
Export only.

Add ability to export values via graphile-export

---

.changeset/stale-schools-press.md
grafast/grafast/src/steps/load.ts
grafast/website/grafast/step-library/standard-steps/loadMany.md
grafast/website/grafast/step-library/standard-steps/loadOne.md
graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts

Following [this discussion in Discord](https://discord.com/channels/489127045289476126/498852330754801666/1217421837206552689) I felt rather motivated to add support for unary steps to loadOne/loadMany.
```ts
const $executorContext = executor.context();
const $id = ...;
const $result = loadOne(list([$executorContext, $id]), async (tuples) => {
// Batch the values by their executor context; probably there will only be one batch entry. (Highly technical note: unary values have been added to `main` recently but not yet shipped; we may be able to get rid of this later by changing the signature of loadOne and declaring $executorContext as a unary value so that you know there will be exactly one value of it - then you will just have `executorContext` and `ids` without this batching overhead.) …
```

Allow loadOne/loadMany to support unary steps

---

postgraphile/website/postgraphile/node-id.md

Added a section to nodeId/relay portion of documentation to clarify that the amber preset also overrides postgraphile's default.
Also included a plugin to revert that, though I can remove that if we think it is too verbose
Following up on discord thread: https://discord.com/channels/489127045289476126/489717163280826374/1220790554334334996
None
None

Clarify amber preset behavior in nodeId documentation

---

postgraphile/website/postgraphile/usage-cli.mdx

Got missed out when the option changed.

Fix 'server' references in CLI docs, should be 'grafserv'

---

grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/mermaid.ts
grafast/grafast/src/planJSONInterfaces.ts
grafast/grafast/src/steps/__flag.ts
graphile-build/graphile-build-pg/src/plugins/PgIntrospectionPlugin.ts
postgraphile/postgraphile/__tests__/mutations/v4/mutation-delete.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/mutation-update.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/relay.createLeftArm.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/simple-single-table-items-root-topic.mermaid
postgraphile/postgraphile/__tests__/queries/v4/large_bigint.issue491.mermaid
postgraphile/postgraphile/__tests__/queries/v4/node.mermaid
postgraphile/postgraphile/__tests__/queries/v4/nodeId-earlyExit.mermaid
postgraphile/postgraphile/__tests__/queries/v4/query.mermaid
postgraphile/postgraphile/__tests__/queries/v4/rbac.basic.mermaid
postgraphile/postgraphile/__tests__/queries/v4/smart_comment_relations.houses.mermaid
postgraphile/postgraphile/__tests__/queries/v4/types-single-node.mermaid
postgraphile/postgraphile/__tests__/queries/v4/types.mermaid

This adds visibility to where dependencies are made with non-standard flags.
Also I made all the inhibit/assert/trap methods generic.
Mermaid only.
None known.

Render flagged dependencies in mermaid

---

.changeset/old-countries-hear.md
.changeset/poor-sheep-itch.md
grafast/grafast/__tests__/trap-test.ts
grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/engine/StepTracker.ts
grafast/grafast/src/engine/executeBucket.ts
grafast/grafast/src/error.ts
grafast/grafast/src/grafastPrint.ts
grafast/grafast/src/steps/__flag.ts
grafast/grafast/src/steps/applyTransforms.ts
grafast/grafast/src/utils.ts
postgraphile/postgraphile/__tests__/queries/polymorphic/relay.polyroot_with_related_poly.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/simple-single-table-items-root-topic.mermaid
postgraphile/postgraphile/__tests__/queries/polymorphic/single-table-items-and-children.mermaid
postgraphile/postgraphile/__tests__/queries/relay/conditionNodeId.mermaid
postgraphile/postgraphile/__tests__/queries/v4/large_bigint.issue491.mermaid
postgraphile/postgraphile/__tests__/queries/v4/node.mermaid
postgraphile/postgraphile/__tests__/queries/v4/nodeId-earlyExit.mermaid
postgraphile/postgraphile/__tests__/queries/v4/query.mermaid
postgraphile/postgraphile/__tests__/queries/v4/rbac.basic.mermaid
postgraphile/postgraphile/__tests__/queries/v4/smart_comment_relations.houses.mermaid
postgraphile/postgraphile/__tests__/queries/v4/types-single-node.mermaid
postgraphile/postgraphile/__tests__/queries/v4/types.mermaid
postgraphile/postgraphile/graphile.config.ts

```ts
trap($step, TRAP_ERROR, { valueForError: "NULL" | "EMPTY_LIST" | "PASS_THROUGH" })
```
When you trap an error or inhibited, you may want to have the value be replaced, either with NULL or EMPTY_LIST. Also, when trapping an error if you just keep it as an error it will immediately be turned back into an error again :man_facepalming: so we now wrap it in `TrappedError` (which does not inherit from `Error` and thus is treated as a value).
Unknown.
None known.

Enable coercion of trapped values

---

.changeset/angry-pugs-design.md
grafast/dataplan-pg/src/steps/pgSelect.ts

The easiest way to get an aggregate would be something like `pgResource.find().clone("aggregate")`; this saves us from having to add APIs like `pgResources.find({}, {mode: "aggregate"})` or `pgResources.findAggregate()`. To make this possible, we now expose the `.clone()` method on `PgSelectStep`.

Expose PgSelectPlan.clone

---

.changeset/moody-balloons-design.md
graphile-build/graphile-utils/src/makeAddPgTableOrderByPlugin.ts
postgraphile/website/postgraphile/make-add-pg-table-order-by-plugin.md

Critical that you set this if you're ordering by something nullable, otherwise cursor pagination won't work across null values because the simpler and cheaper equality check is used without any null fiddling.
(Advice: don't order by nullable things!)

orderByAscDesc now accepts `nullable?: boolean` and defaults true if `nulls` is set

---

grafast/website/grafast/step-library/dataplan-pg/pgSelect.md

Small pr that updates the documentation for `$pgSelectSingle.record()` method. More precisely, it adds an example that demonstrates how to debug an application using this method. 
None
None

chore: update docs for pgSelectSingle.record()

---

.changeset/strange-schools-act.md
grafast/grafast/src/engine/executeBucket.ts

Reported by @Dodobibi via Discord:
https://discord.com/channels/489127045289476126/953710447087980654/1238107976984694794
Fixes major performance issue.
Improvement?

Ensure unary steps only perform unbatched execution once

---

grafast/website/grafast/step-library/dataplan-pg/withPgClient.md

Update `withPgClient` example to include the necessary imports. 
None
None

chore: add withPgClient import in docs

---

.changeset/violet-planets-bow.md
grafast/grafast/src/prepare.ts
postgraphile/postgraphile/graphile.config.ts

Fix bug handling errors in subscribePlan execution

---

postgraphile/website/postgraphile/behavior.md
postgraphile/website/postgraphile/crud-mutations.md

As documented in [behaviors to avoid](
https://postgraphile.org/postgraphile/next/behavior#behaviors-to-avoid ), `insert` is preferred over `create`.
resolves #2078
N/A
N/A

docs: change `create` to `insert`

---

postgraphile/website/postgraphile/polymorphism.md

This was mentioned by @benjie in #2077 and #2083 but does not appear to have been explicitly documented yet.
These changes were not discussed beforehand so do let me know if these docs should not be added or are added to the wrong place.
N/A
N/A

docs: CRUD mutations are not generated for polymorphic types

---

postgraphile/website/postgraphile/node-id.md
postgraphile/website/postgraphile/smart-tags.md

[@benjie additionally notes](
https://github.com/graphile/crystal/issues/2086#issuecomment-2156413952 ) that the requirement to use the table record type (rather than the pk type) in the function definition will hopefully be lifted in the future. However, as this is not yet possible, I excluded this bit of "trivia".
resolves #2086
N/A
N/A

docs: explain how to use global object identifier with functions

---

.changeset/empty-needles-press.md
grafast/dataplan-pg/src/steps/pgClassExpression.ts

We already had `.toSQL()`; this adds the symbol that pg-sql2 requires to know that this is safe to do.
None known.
None known.

Allow pgClassExpressions to be embedded directly into SQL expressions

---

.changeset/curvy-lions-shave.md
grafast/grafserv/src/options.ts
postgraphile/postgraphile/graphile.config.ts

While trying out bun, I found that the log output did not look very nice. After doing some digging, I found that the main reason was that bun displays a piece of the code from where the error originates whereas node simply prints the message line.
node:
```
Masked GraphQL error (hash: 'wiy-9FuoG4YyjQDsoOgPm0ivhaQ', id: 'CDPY2NZ8ZL') error: permission denied for table authenticated_only
at /home/felix/private/labelt/node_modules/pg/lib/client.js:526:17
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async PgExecutor._executeWithClient (/home/felix/private/labelt/node_modules/@dataplan/pg/dist/executor.js:48:27)
at async /home/felix/private/labelt/node_modules/@dataplan/pg/dist/adaptors/pg.js:187:36
at async withPgClient …
```

fix: add newline between parts when logging masked error

---

.changeset/quiet-rocks-draw.md
grafast/grafast/__tests__/types-test.ts
grafast/grafast/src/steps/__flag.ts
grafast/grafast/src/steps/__item.ts
grafast/grafast/src/steps/__value.ts
grafast/grafast/src/steps/listen.ts

Turns out using `: never` like this means that `typeof __ValueStep<Grafast.Context> extends ExecutableStep<infer U> ? U : never` resolves to `unknown` rather than `Grafast.Context`. Fixed in other places too.

Fix more type inference issues by not using never on execute

---

.changeset/metal-llamas-sell.md
grafast/grafast/src/args.ts

If we mutate context in tests, we want to be able to read the mutated context back. We could do that with sub-keys, but meh.

Don't clone context unless we have to

---

.changeset/cold-seahorses-sell.md
.changeset/eight-poems-sniff.md
grafast/dataplan-pg/src/adaptors/pg.ts
grafast/dataplan-pg/src/interfaces.ts
grafast/website/grafast/step-library/dataplan-pg/adaptors.md
postgraphile/postgraphile/src/cli.ts
postgraphile/website/postgraphile/config.mdx

This is an alternative fix to #2104.
`@dataplan/pg` adaptors expose two main methods, which (deliberately) accept different sets of options:
- `makePgService()` - responsible for creating an optimized `PgService` object
- `createWithPgClient()` - creates `withPgClient` functions on the fly via `adaptorSettings`
We currently only have one adaptor, `@dataplan/pg/adaptors/pg`, but this is likely to change over time. From here on we'll talk about the methods in this adaptor specifically, although the reasoning is likely applicable to future adaptors too.
`makePgService()` does not accept an `adaptorSettings` object, nor all of the keys thereof; one example why is that it would be inappropriate for `makePgService` to accept a `pgClient` to use for all requests (it could lead to parallel …

Allow accepting poolConfig via makePgService

---

grafast/grafast/src/engine/OutputPlan.ts
grafast/grafast/src/grafastGraphql.ts

This removes our optimization but in doing so it makes the code easier to refactor. We'll need that for some upcoming changes. We may re-introduce the optimization in later releases, likely after v5.0.0 has gone live.

OutputPlan rewritten to use TypeScript rather than eval'd JS

---

grafast/grafast/__tests__/trap-test.ts

This is a WIP demonstrating that trying to trapi errors that where produced by sideEffects is currently not working.
unknown
unknown

Handle trapping errors produced by sideEffect steps

---

.changeset/smart-months-deliver.md
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-errors.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-errors.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-recursive.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-recursive.mermaid
grafast/grafast/src/steps/graphqlResolver.ts

Since resolvers take ResolveInfo as the third argument, they cannot be deduplicated. If we could know for certain it's not being used then we could, but alas even things like `resolver.length` aren't reliable here due to `arguments` special variable, and `...rest` parameters. For safety, we must assume resolvers can never be deduplicated.

Resolvers should never deduplicate

---

.changeset/cool-oranges-grab.md
grafast/dataplan-pg/src/examples/exampleSchema.ts
grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/step.ts

Fixes https://github.com/benjie/ouch-my-finger/pull/13
Setting `$step.hasSideEffects = true` on a step is only allowed just after the step is created (or during its creation) because we track the fact of a side effect having happened in the layer plan so that all future steps are implicitly "dependent" on the side effect.
However, this check was too strict - it's okay for other steps to have been created, so long as `$step` ultimately depends on them. We just want to make it so that future steps (those that `$step` does not depend on) will implicitly depend on `$step` succeeding. This has been fixed.
Related; when a planning error occurs we "roll back" the plan diagram to a previous state (throwing away older steps). However; when we did this, we did not clear the fact that we were …

Fix issues with planning errors and hasSideEffects=true

---

.changeset/funny-colts-whisper.md
graphile-build/graphile-build/src/global.ts
graphile-build/graphile-build/src/newWithHooks/index.ts

Fixes #2035 (partially).
None known.
None known.

Add Self.name and scope.valueName to context for GraphQLEnumType_values_value hook

---

.changeset/purple-squids-bow.md
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-messages.deopt.sql
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-single-message-evolve.deopt.sql
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts
postgraphile/postgraphile/__tests__/mutations/v4/mutation-create.sql
postgraphile/postgraphile/__tests__/mutations/v4/mutation-update.sql
postgraphile/postgraphile/__tests__/mutations/v4/types.sql

Fixes #2079; verified by making the mod manually in `node_modules` of a reproduction.
Marginal.
None known.

Don't use cache in subscription or mutation mode

---

.changeset/cold-mails-lick.md
.changeset/healthy-windows-cheat.md
graphile-build/graphile-build-pg/src/plugins/PgBasicsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgPolymorphismPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts
postgraphile/postgraphile/__tests__/schema/v4/js-reserved.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/js-reserved.1.graphql
postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.graphql
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql

Fixes #2085
Negligible.
Improvement?

Fix bug in relational polymorphism where the polymorphic relations were nonsensically added to concrete types

---

.changeset/cuddly-rivers-destroy.md
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.deopt.sql
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.json5
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.mermaid
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.sql
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-18.test.graphql
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.deopt.sql
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.json5
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.mermaid
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.sql
grafast/dataplan-pg/__tests__/queries/unions-table/by-id-987654321.test.graphql
grafast/dataplan-pg/src/examples/exampleSchema.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts
graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts

Fixes #2148
Negligible.
Improvement?

Fix bug where `pgUnionAll().single()` would raise an error if no rows were found

---

.changeset/polite-cats-flow.md
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.deopt.sql
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.json5
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.mermaid
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.sql
grafast/dataplan-pg/__tests__/queries/super-simple/unique-forum-message.test.graphql
grafast/dataplan-pg/src/examples/exampleSchema.ts
grafast/dataplan-pg/src/steps/pgSelect.ts

Fixes #2131 
Improvement.
Unknown.

Remove unnecessary check in PgSelect optimize

---

postgraphile/website/postgraphile/make-add-pg-table-condition-plugin.md

Adds the missing `.get()` to the second `makeAddPgTableConditionPlugin` example.
None
None
N/A

Fix `value.get()` typo in `makeAddPgTableConditionPlugin` example

---

.changeset/lemon-ears-grab.md
graphile-build/graphile-build-pg/src/plugins/PgFirstLastBeforeAfterArgsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgProceduresPlugin.ts
postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.subscriptions.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/foreignKey-smart-tag-autofix.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/foreignKey-smart-tag-good.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/function-clash-with-tags-file-workaround.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/function-clash.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/indexes.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/inflect-core.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/noDefaultMutations.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/rbac.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/rbac.ignore.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/relay1.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/simple-collections.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/simple-collections.only.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/simplePrint.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.graphql
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql
postgraphile/postgraphile/src/plugins/PgV4SmartTagsPlugin.ts
postgraphile/postgraphile/src/presets/v4.ts
postgraphile/website/postgraphile/behavior.md

Fixes https://github.com/graphile/graphile-engine/issues/713
Negligible.
Improvement.

Disable backward pagination of functions by default

---

grafast/website/grafast/step-library/dataplan-pg/pgSelect.md
grafast/website/grafast/step-library/standard-steps/applyTransforms.md
grafast/website/grafast/step-library/standard-steps/each.md

In my usage of Grafast at my workplace for the past few months, I've fallen in love with it. I've also obtained some learnings that I wish I had read in the docs. This is focused mainly around modifying the keys/values returned from a `PgSelect`. We have been working through the unique case of having to support a legacy GraphQL schema while not wanting that to affect our database design. This meant writing plans to resolve fields that required changing the returned keys and values from the DB a lot. 
Hopefully, these changes might help others that run into similar use-cases.
- Add a new docs page for the ApplyTransforms step 
- Add a new section in the each step docs with more example usage
- Add a new section in PgSelect to link to each and applyTransforms to describe additional behavior …

Add Documentation for ApplyTransforms, and Add Resources to Each and PgSelect Docs

---

.changeset/quiet-items-divide.md
utils/graphile-export/src/wellKnown.ts

I noticed an issue where some modules weren't being exported properly. [Full discord discussion here](https://discord.com/channels/489127045289476126/498852330754801666/1286380009379856465).
My source code has:
```ts
import CityTimezones from 'city-timezones';
import snakeCase from 'lodash/snakeCase';
...
export const pgInsert = EXPORTABLE((snakeCase) => async (pgClient, table, data) => {
const columns = Object.keys(data).map(snakeCase).join(', ');
...
}, [snakeCase]);
```
and I'm exporting modules like:
```ts
import * as CityTimezones from 'city-timezones';
import * as lodashSnakeCase from 'lodash/snakeCase';
...
await exportSchema(schema, exportFileLocation, {
mode: "typeDefs",
modules: {
'city-timezones': CityTimezones,
'lodash/snakeCase': lodashSnakeCase,
}
});
```
But my exported …

Remove default filter from WellKnownMap

---

.changeset/nine-ladybugs-guess.md
.changeset/polite-cherries-exercise.md
postgraphile/postgraphile/src/presets/v4.ts
utils/graphile-config/src/resolvePresets.ts

Fixes https://github.com/graphile/crystal-pre-merge/issues/415
Some subtle issues with plugin/preset ordering/etc may be surfaced, plus this fixes a bug so anyone relying on the bug may have their configuration's tweaked - recommend fingerprinting your schema before and after this change and look for differences.
Startup costs increased.
None known.

V4 preset should use Amber preset

---

.changeset/pretty-knives-crash.md
grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/operationPlan-input.ts
grafast/grafast/src/utils.ts

Fixes https://github.com/graphile/crystal-pre-merge/issues/501
Planning costs increased.
None known.

More assertNotAsync calls

---

.changeset/famous-birds-promise.md
grafast/grafast/__tests__/loadOne-test.ts
grafast/grafast/src/multistep.ts
grafast/grafast/src/steps/list.ts
grafast/grafast/src/steps/load.ts
grafast/grafast/src/steps/object.ts

Fixes https://github.com/graphile/crystal/issues/2170
Marginal performance cost for loadOne/loadMany calls that accept object/list specs.
Generally an improvement I hope, though there's a risk of memory exhaustion attacks if this is not used sensibly.

Enable stabilization of objects/lists going through loadMany/loadOne multistep

---

.changeset/gold-games-live.md
graphile-build/graphile-build-pg/src/plugins/PgBasicsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgConditionArgumentPlugin.ts
graphile-build/graphile-build/src/behavior.ts

Reflects issues found whilst adding support into plugins.

Adjust some of the behavior overhaul changes

---

postgraphile/website/postgraphile/jwk-verification.md
postgraphile/website/versioned_docs/version-4.x/jwk-verification.md

In recent versions of [`express-jwt`](https://www.npmjs.com/package/express-jwt) the name of the property in the request object where the JWT payload is set defaults to `req.auth`
This PR also renames the `scope` claim to better align with the decoded JWT payload example in the documentation proceeding it.
N/A
N/A

docs: update express-jwt auth property name in examples

---

graphile-build/graphile-build-pg/src/plugins/PgIndexBehaviorsPlugin.ts
graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts

DON'T MERGE THIS.
Relations have `connection`, `list` and `single` behaviors, but if you just want to turn off using the relation really you just want to do `-select`. Similarly, if you're querying a relation via filter or similar you don't necessarily care whether it's presented as a list or a connection, you just want to know if it's allowed or not. This should be `select`, probably? And as mentioned elsewhere, the behavior system should have implications, like `-select` should imply `-connection -list -single`.

Relations have no basic `select` behavior

---

grafast/website/README.md
grafast/website/grafast/step-classes.md
grafast/website/grafast/step-library/dataplan-pg/registry/codecs.md
grafast/website/grafast/step-library/index.md
grafast/website/grafast/step-library/standard-steps/index.mdx
grafast/website/grafast/step-library/standard-steps/lambda.md
grafast/website/grafast/step-library/standard-steps/list.md
grafast/website/grafserv/servers/index.mdx

Needs review! 
- detail on implementing `at` and `get` added under the header "Access methods" 
- added missing detail about the methods a ListStep can accept
- Saw a missing link while reviewing the methods for a Lambda step
Closes https://github.com/graphile/crystal-pre-merge/issues/497

docs: documentation for at() and get() methods

---

.changeset/poor-countries-argue.md
utils/pg-introspection/src/acl.ts
utils/pg-introspection/src/introspection.ts

Also refactors some constants for better TypeScript hover info.
Introspection query results in more data being pulled, slowing initial startup.
Introspection query now include RLS policies, which are sensitive. However, it already included grants so I don't think this is a big deal.

Add support for introspecting RLS policies

---

.changeset/yellow-students-glow.md
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgSelectSingle.ts
grafast/ruru-components/tsconfig.json
graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts

https://discord.com/channels/489127045289476126/498852330754801666/1312193983308365865
I think I found a potential edge case, wondering your thoughts on it. I have two plans implemented in  makeExtendedScemaPlugin, both are implemented manually with calling pgSelect with a custom from function. I'm calling both of them in a query and I think they're getting deduplicated, even though from implementation is different.
unknown. Theoretically it would deduplicate _less_ than before, but I think that any such deduplications would have been erroneous.
unknown, but don't expect it to change anything.

Added checks for "from" field in pgSelect dedup function

---

.changeset/five-dogs-rest.md
graphile-build/graphile-build-pg/src/plugins/PgAttributesPlugin.ts
postgraphile/postgraphile/src/plugins/PgV4InflectionPlugin.ts
postgraphile/postgraphile/src/presets/relay.ts
postgraphile/postgraphile/src/presets/v4.ts

V4 explicitly does `skipRowId` to force reproduction of a bug in the inflection:
https://github.com/graphile/graphile-engine/blob/e2a8a7cae58ff26947c050505c76c4a30cfe21c6/packages/graphile-build-pg/src/plugins/PgBasicsPlugin.js#L466-L471
This PR better reflects this same change correctly.
It also removes the `_joinAttributeNames` override - it doesn't seem to actually be required, and in fact causes issues in third party plugins compatibility.
See previous PR:
- https://github.com/graphile/crystal/pull/2251 
Negligible.
None known.

Tweak the way _attributeName works again

---

postgraphile/website/postgraphile/usage-schema.md

The documentation was using deprecated interfaces. With this update
1. It uses new `hookArgs`, where you can pass `resolvedPreset`,  `requestContext` with the args.
2. It uses `TypedDocumentNode` from `@graphql-typed-document-node/core`, to support fully typed queries when using graphql-codegen's `client-preset`.
Note:
The return type of `execute` function is `PromiseOrValue<ExecutionResult | AsyncGenerator<AsyncExecutionResult, void, undefined>>`, but I didn't found `AsyncExecutionResult` so the type in the current example supports only `ExecutionResult`.

Update `usage-schema.md` example

---

grafast/grafast/.well-known/funding-manifest-urls
grafast/grafserv/.well-known/funding-manifest-urls
grafast/ruru/.well-known/funding-manifest-urls
graphile-build/graphile-build/.well-known/funding-manifest-urls
postgraphile/postgraphile/.well-known/funding-manifest-urls
utils/.well-known/funding-manifest-urls

Looks like we also need these files to show our ownership of these repos. Works in tandem with https://github.com/graphile/graphile.github.io/pull/424

funding: Funding manifest URIs for each crystal repo

---

utils/graphile-config/src/middleware.ts
utils/website/graphile-config/preset.md

Addresses https://github.com/graphile/crystal/issues/2286
When reading through the middleware code, I also noticed one variable was somewhat confusingly named. I recommend changing it to activityName. Happy to do it in another PR or not do it if you'd rather not mix docs with this nitpick code change
Note that running `yarn prettier 'utils/website/graphile-config/preset.md' --write` with the `proseWrap: "preserve",` commented out also seemed to adjust a few newlines.
Just docs
None

adding a callout to graphile config docs re merging exists-but-undefined options

---

.changeset/blue-pumpkins-smile.md
.changeset/violet-months-suffer.md
grafast/dataplan-pg/src/steps/pgPolymorphic.ts
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts
grafast/grafast/src/step.ts
grafast/grafast/src/steps/__inputDynamicScalar.ts
grafast/grafast/src/steps/__trackedValue.ts
grafast/grafast/src/steps/connection.ts
grafast/grafast/src/steps/constant.ts
grafast/grafast/src/steps/list.ts
grafast/grafast/src/steps/listTransform.ts
grafast/grafast/src/steps/object.ts
grafast/grafast/src/steps/polymorphicBranch.ts

Grafast changes:
- update: `ExecutableStep::getDep` is now generic so you don't need to `this.getDep(n) as ExpectedThing` and can instead `this.getDep<ExpectedThing>(n)`
- added: `ExecutableStep::maybeGetDep<TStep>(n)` for when `n` may not be set - returns `null` if `n == null`
- added: `ExecutableStep::getDepOrConstant(n, fallback)`: returns `this.maybeGetDep(n) ?? constant(fallback)`
Then refactored the code to use these helpers.
Negligible.
Seems unlikely. If anything an improvement because less code is written and thus less risk of copy/paste errors.

Grafast: simplify dep-fetching code with generics and helpers

---

.changeset/great-keys-film.md
grafast/dataplan-pg/__tests__/mutations/withPgClient/multipleActions.deopt.mermaid
grafast/dataplan-pg/__tests__/mutations/withPgClient/multipleActions.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-errors.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-errors.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-recursive.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object-recursive.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics-object.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/basics.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/objectDefaults.deopt.mermaid
grafast/dataplan-pg/__tests__/queries/resolvers/objectDefaults.mermaid
grafast/grafast/src/inspect.ts
grafast/grafast/src/steps/constant.ts
postgraphile/postgraphile/__tests__/mutations/v4/enum_tables.mutations.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/geometry.mutations.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/mutation-create.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/pg11.types.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/procedure-mutation.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/rbac.createPerson.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/rbac.leftArmIdentity.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/rbac.updatePerson.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/types.mermaid
postgraphile/postgraphile/__tests__/queries/v4/procedure-computed-fields-cut-down-for-export.mermaid
postgraphile/postgraphile/__tests__/queries/v4/procedure-computed-fields.mermaid
postgraphile/postgraphile/__tests__/queries/v4/procedure-query.mermaid
postgraphile/postgraphile/__tests__/queries/v4/space.mermaid

Enables more `inspect()` properties and replaces `[Object: null prototype]` in output with `§` to simplify plan diagrams.

Simplify `constant()` printing

---

.changeset/purple-owls-vanish.md
grafast/grafast/src/engine/OperationPlan.ts

Otherwise a cacheKey of `1` is seen as equivalent to `"1"`. This also allows booleans, null, undefined, and complex values to be used as keys.

Allow step cache to use more keys (avoid string/number conflict)

---

.changeset/dull-moles-exercise.md
.changeset/fuzzy-tigers-scream.md
.changeset/serious-sheep-confess.md
grafast/dataplan-pg/src/interfaces.ts
grafast/dataplan-pg/src/pgLocker.ts
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgSelectSingle.ts
grafast/dataplan-pg/src/steps/pgStmt.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts
grafast/dataplan-pg/src/utils.ts

Using the new `sql.withTransformer` feature introduced in #2320, we can make it so that references to postgres typed steps can be made directly in scoped `sql` fragments rather than having to use `$pgSelect.placeholder()`:
```diff
User: {
posts($user, { $forumId }) {
const $id = $user.get('id');
const $posts = posts.find();
-      $posts.where(sql`author_id = ${$posts.placeholder($id)} and forum_id = ${$posts.placeholder($forumId)}`);
+      $posts.where(sql => sql`author_id = ${$id} and forum_id = ${$forumId}`);
return $posts;
},
},
```
The code under the hood is equivalent, a transformer will detect `$id` and `$forumId` are typed PG steps and will replace them with `$posts.placeholder($id)` or `$posts.placeholder($forumId)` automatically.
Negligible.
None known.

Add scopedSQL to various of our classes

---

.changeset/fast-phones-change.md
grafast/grafast/__tests__/unaryDeps-test.ts
grafast/grafast/src/engine/executeBucket.ts
grafast/grafast/src/interfaces.ts
grafast/grafast/src/steps/applyTransforms.ts
grafast/grafast/src/steps/listTransform.ts

ExecutionValue comes in two flavours: batch and unary. Unary has a `.value` and batch has a `.entries`. Previously we included `: never` versions of each of these to make access easier, but this could lead to mistakes. This interface has been removed (:rotating_light: breaking! but only the types) so you'll need to narrow via .isBatch before you can use the relevant property.
When you knew an execution value was unary, you could use `.at(0)` to access its value; however this was risky because there was no assertion that the value is unary. To help mitigate this, I've added the new `.unaryValue()` method which asserts that the value is unary and then accesses the singular value from it; this should make code safer when you know a `$step` should be unary due to calling …

Add `.unaryValue` to ExecutionValue

---

.changeset/dirty-dancers-eat.md
grafast/dataplan-pg/__tests__/helpers.ts
utils/pg-sql2/src/index.ts

Marginal decrease in pg-sql2 performance, not sure if it is likely to be measurable but I know from past experience that this isn't quite as fast.
Negligible.

Fix bug in pg-sql2 optimization causing $$type access to throw on null/undefined

---

.changeset/purple-suns-explode.md
grafast/grafast/src/engine/OutputPlan.ts

When working on #2339 I got into a situation where the cursors were invalid and thrown an error; but that error was then passed to `processRoot` which resulted in `undefined` error; which we then threw. Made little sense.
This PR moves the error check earlier... I don't think we want errors going through processRoot?
Marginal.
None known.

Handle errors before performing processRoot

---

.changeset/honest-goats-learn.md
utils/pg-sql2/src/index.ts

As above
Types only.
Types only.

Mark a few of the pg-sql2 inputs as readonly

---

grafast/website/grafast/plan-diagrams.mdx

Explain how to enable plans in grafast
As discussed here.
https://discord.com/channels/489127045289476126/1325736426587033652/1325875935060299876

Update grafast plan diagram doc to include explain option

---

.changeset/lemon-geckos-sit.md
.changeset/slimy-elephants-explain.md
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts

PgSelectStep and PgUnionAllStep had ugly constructors that were overloaded to allow for cloning versus creating new steps. Horrible.
This PR creates new static clone methods instead, and refactors the constructor to be simpler.
This technically isn't a breaking change because people should not be constructing classes directly, they should be using the helper functions as detailed in the docs. And even if they are constructing the classes directly they shouldn't be using that for cloning.
Marginal?
If there's bugs in this, the bugs could be unpleasant.

Cleaner cloner

---

.changeset/sweet-bulldogs-share.md
.changeset/swift-elephants-destroy.md
grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/engine/lib/defaultPlanResolver.ts
grafast/grafast/src/index.ts
grafast/grafast/src/interfaces.ts
graphile-build/graphile-utils/src/makeWrapPlansPlugin.ts

This changes us to using a static default plan resolver (rather than generating a new one per field) by adding the `fieldName` to the plan info. We also update `graphile-utils` to use this new default plan resolver rather than using its own (inconsistent!) default.
Fixes #2306
Maybe better? Less memory allocation, I expect?
Unlikely.

Fix default plan resolvers

---

.changeset/mean-pugs-sell.md
grafast/grafast/__tests__/grafastSync.test.ts
grafast/grafast/src/engine/executeBucket.ts

`grafastSync` should be able to execute mutation operations if those operations only use synchronous steps.
Negligible
None known.

Allow mutations to complete synchronously

---

postgraphile/website/versioned_docs/version-4/custom-queries.md
postgraphile/website/versioned_docs/version-4/smart-tags.md

I had some difficulty discovering from the docs that I could apply smart tags to attributes on custom postgres types, in addition to table columns. As discussed on [discord](https://discordapp.com/channels/489127045289476126/1343635302694129734), I've made a few small additions to the documentation in the areas I had looked to try and make that functionality a bit more obvious.

Postgres Type Attribute Nullability Documentation

---

.changeset/funny-ghosts-tap.md
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgStmt.ts
grafast/grafast/src/input.ts
grafast/grafast/src/steps/connection.ts
grafast/website/grafast/step-library/standard-steps/connection.md
postgraphile/postgraphile/__tests__/mutations/v4/mutation-create.single-variables.mermaid
postgraphile/postgraphile/__tests__/mutations/v4/mutation-create.single-variables.sql
postgraphile/postgraphile/__tests__/queries/v4/connections.variables.mermaid
postgraphile/postgraphile/__tests__/queries/v4/issue2210.mermaid

Cursors are not processed fully at runtime, removing the need for plan-time evaluation and branching.
Moves logic from plan-time to runtime. Reduces number of times operation needs to be planned.
Reduces number of times operation needs to be planned :+1:

Process cursors without using step evaluation

---

.changeset/mean-ads-develop.md
grafast/grafast/src/steps/__inputDynamicScalar.ts
grafast/grafast/src/steps/__inputList.ts
grafast/grafast/src/steps/__inputObject.ts
grafast/grafast/src/steps/__inputStaticLeaf.ts
grafast/grafast/src/steps/__trackedValue.ts
grafast/grafast/src/steps/constant.ts

Long term aim is to completely remove eval. For now, we'll settle for just using it for `@skip`, `@include`, `@defer` and `@stream` `if:` evaluation
None.
Helps guide people away from using `$input.eval*()`, which avoids plan branching, helping to avoid DOS through plan explosion.

Mark all eval methods as internal

---

.changeset/silent-jars-greet.md
grafast/dataplan-pg/src/steps/pgPolymorphic.ts
grafast/dataplan-pg/src/steps/pgSelect.ts
grafast/dataplan-pg/src/steps/pgUnionAll.ts
grafast/grafast/src/engine/OutputPlan.ts
grafast/grafast/src/interfaces.ts
grafast/grafast/src/step.ts
grafast/grafast/src/steps/__flag.ts
grafast/grafast/src/steps/__inputDynamicScalar.ts
grafast/grafast/src/steps/__trackedValue.ts
grafast/grafast/src/steps/access.ts
grafast/grafast/src/steps/connection.ts
grafast/grafast/src/steps/listTransform.ts
grafast/grafast/src/steps/object.ts
grafast/grafast/src/steps/polymorphicBranch.ts

When we introduced step flagging, we had it so that a step could be added as a dependency along with flags, for example "inhibit on null". But this left us with a bit of a predicament... what if you `.getDep(0)` to get this dependency, and then try and add it to a copy of yourself? Now the "inhibit on null" has gone missing!
To solve this, we had `.getDep(0)` return the step _wrapped_ in a `__FlagStep` (if necessary) to ensure that anything else that added this dependency would have the flags maintained.
This was great, except it meant that sometimes you would get a `__FlagStep` when you're expecting, for example, a PgSelectSingleStep, and your code would go wrong. So we also gave you a new method `.getDepOptions(0)` which would let you fetch this dependency along with its flags. It's …

Be stricter about types and usage of getDep/getDepOptions

---

grafast/grafserv/src/servers/h3/v1/index.ts
yarn.lock

This is a types-only fix, so no need for changeset.

Remove TS hack now graphql-ws fix is released

---

grafast/website/grafast/step-library/standard-steps/context.md

Adds documentation for extending the default grafast context for having type safety in the access patterns of the `context` step.
Discussed on discord, [link](https://discord.com/channels/489127045289476126/498852330754801666/1349800186272153712)
None
None

add docs for making context type-safe

---

grafast/website/news/2023-10-13-grafast-0.1.mdx
grafast/website/news/2025-03-24-grafast-0.1-beta.21.mdx
grafast/website/src/css/common.module.css

At the moment, this is a straight copy of the graphile.org site with just the relevant bits for each project. I suspect there should be some expanding or wording change. If we get this live this week, we can send out a mailing list update. At the moment, we've only really shared news of this release to sponsors.

news: Add news items to postgraphile.org and grafast.org about the major beta release

---

.changeset/early-worms-eat.md
grafast/grafast/src/envelop.ts
grafast/grafserv/src/index.ts
grafast/grafserv/src/servers/node/index.ts
grafast/grafserv/src/utils.ts
graphile-build/graphile-build-pg/package.json
graphile-build/graphile-build-pg/src/examples/benjies-test-script.ts
graphile-build/graphile-build-pg/tsconfig.json
yarn.lock

In V4 we had `normalizedConnectionParams` which could be used to read connectionParams (an arbitrary JSON object) as if they were headers (i.e. with lowercase keys). This PR adds that.
Small processing overhead for websocket requests.
Enables users to easily read the normalized params, thus a benefit.
It _does_ combine values if there is mixed case, so potentially risky but I can't think of a situation in which this would be problematic.

Add normalizedConnectionParams

---

.changeset/icy-views-care.md
grafast/grafserv/src/options.ts

Naked GraphQL errors, such as those generated by coercion, are now treated as safe.
Negligible.
Potentially quite high depending on what values fail to coerce and how GraphQL presents them in the error message; however this will always be the fault of the schema developer and isn't an inherent flaw in Grafast.

Naked GraphQLErrors are safe

---

grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/interfaces.ts
grafast/grafast/src/operationPlan-input.ts
grafast/grafast/src/steps/graphqlResolver.ts

For some reason trackedArguments used to to be an indirect object with get function, but going forward we don't need this complexity; let's remove it.

Uncomplicate trackedArguments

---

.changeset/two-ears-pull.md
grafast/grafast/__tests__/dcc/queries/floor-minimal.json5
grafast/grafast/__tests__/dcc/queries/floor-minimal.test.graphql
grafast/grafast/src/engine/executeBucket.ts

`undefined` values should get `FLAG_NULL`, but this wasn't always the case. The result is that `inhibitOnNull` wouldn't always inhibit when undefined. This fixes that.

Ensure undefined values are flagged correctl

---

.changeset/wise-pigs-slide.md
graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts
postgraphile/postgraphile/__tests__/kitchen-sink-data.sql
postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql
postgraphile/postgraphile/__tests__/queries/refs/books-editors-plural-ref.json5
postgraphile/postgraphile/__tests__/queries/refs/books-editors-plural-ref.mermaid
postgraphile/postgraphile/__tests__/queries/refs/books-editors-plural-ref.sql
postgraphile/postgraphile/__tests__/queries/refs/books-editors-plural-ref.test.graphql
postgraphile/postgraphile/__tests__/queries/refs/books-related-people-plural-ref.json5
postgraphile/postgraphile/__tests__/queries/refs/books-related-people-plural-ref.mermaid
postgraphile/postgraphile/__tests__/queries/refs/books-related-people-plural-ref.sql
postgraphile/postgraphile/__tests__/queries/refs/books-related-people-plural-ref.test.graphql
postgraphile/postgraphile/__tests__/queries/refs/posts-author-singular-ref.json5
postgraphile/postgraphile/__tests__/queries/refs/posts-author-singular-ref.mermaid
postgraphile/postgraphile/__tests__/queries/refs/posts-author-singular-ref.sql
postgraphile/postgraphile/__tests__/queries/refs/posts-author-singular-ref.test.graphql
postgraphile/postgraphile/__tests__/schema/v4/refs.1.export.mjs
postgraphile/postgraphile/__tests__/schema/v4/refs.1.graphql

`pgUnionAll` was incorrectly being used, we needed to build our own union all to make multi-path refs work without polymorphism.
<details>
<summary>Original message</summary>
This PR adds 3 test suites related to [issue #2496](https://github.com/graphile/crystal/issues/2496).
- ✅ 2 test suites are expected to **pass**
- ❌ 1 test suite is expected to **fail**, as it reproduces the current bug
These tests were requested by the maintainer to help reproduce and fix the issue.
</details>

Fix issue with multi-path refs to non-polymorphic types

---

.changeset/plenty-carrots-arrive.md
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-messages.deopt.mermaid
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-messages.mermaid
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-single-message-evolve.deopt.mermaid
grafast/dataplan-pg/__tests__/subscriptions/basics/forum-single-message-evolve.mermaid
grafast/grafast/src/engine/LayerPlan.ts
grafast/grafast/src/engine/OperationPlan.ts
grafast/grafast/src/engine/OutputPlan.ts
grafast/grafast/src/engine/executeBucket.ts
grafast/grafast/src/prepare.ts
grafast/grafast/src/utils.ts

Discovered thanks to @jemgillam's test suite which, due to using very simple access methods, triggered a lot of issues in our optimizations which our more complex PostGraphile queries weren't triggering!
Also fixes an issue with combined layer plans inside of `@stream`'d layer plans, whereby the data would never be output. This was an issue I was expecting and was holding up the release, but we had to fix the other issues to be able to reproduce it. This is now reproduced and fixed. (Since that issue never made it out, I've omitted it from the changelog.)

Fix a number of bugs relating to incremental delivery

---

grafast/website/grafast/step-library/standard-steps/error.md
grafast/website/grafast/step-library/standard-steps/index.mdx

Users are never going to need this now we don't have `$step.eval*()`. They can just use a lambda to throw if they really want.

Remove error step from documentation

---

grafast/grafast/src/engine/executeBucket.ts

Arrays were going through our async iterable loop to allow for stream, but if we're not using stream this is unnecessarily slow. This introduces a "fast" version for arrays that does less work.
It also catches errors when starting the generator.

Fast mode for array looping

---

.changeset/open-pugs-lose.md
grafast/ruru-components/src/hooks/useFetcher.ts
grafast/website/src/components/Playground/PlaygroundInner.jsx

Can now supply typeDefs via code, and enable defer and stream:
```ts
const typeDefs = `
type Query {
addTwoNumbers(a: Int!, b: Int!): Int
list: [Int]
}
`;
const objects = {
Query: {
plans: {
addTwoNumbers(_, { $a, $b }) {
return lambda([$a, $b], ([a, b]) => a + b, true);
},
list() {
return constant([1,2,3])
}
},
},
};
const enableDeferStream = true;
```
This also fixes ruru to hide extensions in incremental delivery results via hard deletion.

Enhance playground

---

grafast/dataplan-pg/src/executor.ts
grafast/website/grafast/step-library/dataplan-pg/registry/resources.md
postgraphile/website/postgraphile/debugging.md

`DEBUG=@dataplan/pg:PgExecutor` should show the SQL/results. `:verbose` includes caching. `:explain` includes explain results.

See SQL without being verbose

---

grafast/website/news/2025-06-07-last-epic-solved.22.mdx
postgraphile/website/news/2025-06-07-last-epic-solved.41.mdx
postgraphile/website/src/pages/v5beta.mdx

We changed the slug of the page on graphile.org but never updated the link from the other webpages!

websites: fix news links

---

.changeset/fuzzy-facts-throw.md
utils/graphile-export/src/exportSchema.ts
utils/graphile-export/src/interfaces.ts

Relates to:
- #2565 
This allows a user to pass `{ disableOptimize: true}` to export and the optimize step will be skipped.

Give Graphile Export a way to disable optimize

---

.changeset/witty-moments-tan.md
utils/graphile-config/src/loadConfig.ts

Previously we only used `interpret` for determining how to process a file; but if we have `--experimental-strip-types` enabled then we should try and use that first as we might not need a loader at all.

Add support for --experimental-trip-types to graphile-config

---

.changeset/wild-beans-count.md
postgraphile/postgraphile/src/presets/amber.ts
postgraphile/postgraphile/src/presets/lazy-jwt.ts
postgraphile/postgraphile/src/presets/relay.ts
postgraphile/postgraphile/src/presets/v4.ts
postgraphile/website/postgraphile/adding-and-replacing-inflectors.md
postgraphile/website/postgraphile/config.mdx
postgraphile/website/postgraphile/migrating-from-v4/index.mdx
postgraphile/website/postgraphile/migrating-from-v4/make-add-inflectors-plugin.md
postgraphile/website/postgraphile/migrating-from-v4/migrating-custom-plugins.md
postgraphile/website/postgraphile/usage-library.md

Fixes #2597 by ensuring that importing amber is enough to import the types.
Also overhauls the library TypeScript example using Node 24 and `npm pkg set` commands.
Imports the root file from the presets, so:
```ts
import { AmberPreset } from 'postgraphile/presets/amber';
export default {
extends: [AmberPreset],
schema: {
// ...
},
}
```
should now be valid according to TypeScript.
Not super happy with this because it pulls in code that's not _necessarily_ needed... But also I can't think when that would matter.
Types only.

Have Amber and V4 presets import types

---

grafast/website/news/2023-10-13-grafast-0.1.mdx
grafast/website/news/2025-03-24-grafast-0.1-beta.21.mdx
grafast/website/news/2025-06-07-last-epic-solved.22.mdx
postgraphile/website/news/2023-08-03-beta-release.mdx
postgraphile/website/news/2025-03-24-beta-40-release.mdx
postgraphile/website/news/2025-06-07-last-epic-solved.41.mdx
postgraphile/website/postgraphile/jwt-guide.mdx
postgraphile/website/postgraphile/live-queries.mdx
postgraphile/website/postgraphile/postgresql-schema-design.mdx
postgraphile/website/postgraphile/quick-start-guide.mdx
postgraphile/website/postgraphile/smart-comments.mdx
postgraphile/website/postgraphile/subscriptions.mdx
postgraphile/website/versioned_docs/version-4/index.mdx
postgraphile/website/versioned_docs/version-4/jwt-guide.mdx
postgraphile/website/versioned_docs/version-4/live-queries.mdx
postgraphile/website/versioned_docs/version-4/postgresql-schema-design.md
postgraphile/website/versioned_docs/version-4/quick-start-guide.mdx
postgraphile/website/versioned_docs/version-4/smart-comments.mdx
postgraphile/website/versioned_docs/version-4/subscriptions.mdx
postgraphile/website/versioned_docs/version-5/jwt-guide.mdx
postgraphile/website/versioned_docs/version-5/live-queries.mdx
postgraphile/website/versioned_docs/version-5/postgresql-schema-design.mdx
postgraphile/website/versioned_docs/version-5/quick-start-guide.mdx
postgraphile/website/versioned_docs/version-5/smart-comments.mdx
postgraphile/website/versioned_docs/version-5/subscriptions.mdx

After the update to Docusaurus 3, we need a few tweaks: 
- update `styles.intro` to use a div instead of p - stops extra p tags from being inserted and fixes the unintentional nesting of ul inside a p block

websites: styles.intro fix after Docusaurus update

---

grafast/dataplan-pg/src/pgServices.ts

Fixes #2609 
unknown - should be none
possibly positive in case user code anywhere is waiting for process exit?
unknown - should be none.
I have no idea how/if this would be tested - sorry, and it's such a tiny change so dunno about the others.

Unref the pgServices cache timer to prevent blocking process exit

---

.changeset/four-weeks-see.md
grafast/grafast/src/index.ts
grafast/grafast/src/interfaces.ts
grafast/grafast/src/steps/applyInput.ts
grafast/grafast/src/steps/bakedInput.ts
grafast/website/grafast/step-library/standard-steps/applyInput.md
graphile-build/graphile-utils/src/makeAddPgTableOrderByPlugin.ts
postgraphile/website/postgraphile/add-pg-table-order-by.md

Fixes:
- #2568
@hos Please a) test this, b) write tests for this, c) scribble up some documentation for this.
Essentially this is to solve the issue you raised. You can:
1. Augment the existing `...OrderBy` type that exists, and give it a `applyScope()` method that returns e.g. `context()` or `object({ locale: get(context(), 'locale') })` or whatever:
```ts
const AddApplyScopeToBlahOrderByPlugin: GraphileConfig.Plugin = {
name: "AddApplyScopeToBlahOrderByPlugin",
schema: {
hooks: {
GraphQLEnumType(config, build, context) {
if (config.name === 'BlahOrderBy') {
const { grafast: { context } } = build;
config.extensions ??= {};
config.extensions.grafast ??= {};
config.extensions.grafast.applyScope = () => context();
}
return config;
}
}
}
}
```
2. Access this via `info.scope` in the …

Theoretically the ability to add a 'scope' to orderBy

---

grafast/grafserv/src/middleware/graphiql.ts
grafast/ruru/src/server.ts
grafast/ruru/src/static.ts
grafast/ruru/webpack.config.mts

- Reduces HTML payload from 4kB to 1.2kB
- Reduces ruru.js from 1.4MB to 1.06MB
- Adds preload for various things

Switch from deflate to brotli, compress HTML on the fly

---

.changeset/petite-turkeys-matter.md
grafast/ruru/src/server.ts

No idea why this works... but it fixes an issue serving Ruru from unpkg.com due to cross-origin permissions issues.

Implement workaround for loading worker files from remote URLs

---

.changeset/tangy-papers-repair.md
utils/eslint-plugin-graphile-export/src/ExhaustiveDeps.ts
utils/eslint-plugin-graphile-export/src/NoNested.ts
utils/eslint-plugin-graphile-export/src/utils.ts

Previously we only supported `EXPORTABLE(...)`; we now also support `build.EXPORTABLE(...)` (i.e. "MemberExpression"s).

Fix eslint-plugin-graphile-export to support member expressions

---

.changeset/cool-news-nail.md
grafast/ruru-components/ruru.css
grafast/ruru-components/src/components/Footer.tsx
grafast/ruru-components/src/hooks/useStorage.ts
grafast/ruru-components/src/ruru.tsx
grafast/ruru/src/server.ts

Normal GraphiQL style has a lot of whitespace, seriously limiting space for editor. This reworks it a bit.

Add condensed mode to Ruru (enabled by default)

---

postgraphile/website/postgraphile/extending.mdx
postgraphile/website/versioned_docs/version-4/examples/index.mdx
postgraphile/website/versioned_docs/version-4/extending.mdx
postgraphile/website/versioned_docs/version-4/plugin-gallery/index.mdx

Add `DocCardList` to some category style pages to make the page make more sense:

PostGraphile website: add DocCardList

---

graphile-build/graphile-utils/__tests__/makeAddPgTableOrderByPlugin.test.ts
postgraphile/website/postgraphile/add-pg-table-order-by.md

Add a test for `addPgTableOrderBy` using scope. And also example code in the docs.

Pg order by plugin apply scope

---

postgraphile/website/src/pages/v5beta.mdx

I missed that the table on the v5 updates page was broken after the Docusaurus update! Two simple braces fix that.

postgraphile website: Fix v5 page

---

.changeset/polite-kids-see.md
grafast/dataplan-pg/src/steps/withPgClient.ts

Fix type of shared/unary arg in loadOneWithPgClient/loadManyWithPgClient

---

.changeset/deep-eels-post.md
grafast/dataplan-pg/src/adaptors/pg.ts
grafast/dataplan-pg/src/executor.ts
grafast/dataplan-pg/src/steps/pgDeleteSingle.ts
grafast/dataplan-pg/src/steps/pgInsertSingle.ts
grafast/dataplan-pg/src/steps/pgUpdateSingle.ts

Fixes #2259
Add ability for Postgres client to capture `RAISE NOTIFY` issued during an SQL
query. An example follows:
Database:
```sql
create table foo (id serial primary key, bar text);
create function tg_foo() returns trigger language plpgsql volatile as $$
begin
raise notice 'Hello World' using hint = 'Hi, ' || NEW.bar;
return NEW;
end;
$$;
create trigger _insert before insert on foo for each row execute function tg_foo();
```
Plugin:
```ts
const plugin = extendSchema({
typeDefs: /* GraphQL */ `
type PgNotice {
severity: String
message: String
code: String
detail: String
hint: String
}
extend type CreateFooPayload {
messages: [PgNotice]
}
`,
plans: {
CreateFooPayload: {
messages($payload: any) {
const $result = get($payload, "result") as PgInsertSingleStep;
return $result.getNotices(); …
```

Capture PostgreSQL notices
