README.md, examples/forum/README.md
I'm going to merge this ASAP, I'll still make any changes suggested here 😊
=> Add readme to forum example

src/graphql/createTableType.js, src/graphql/query/createQueryFields.js, src/graphql/query/createQueryType.js, src/graphql/query/createSingleQueryField.js, tests/graphql/createTableType.test.js, tests/graphql/query/createQueryFields.test.js, tests/graphql/query/createSingleQueryField.test.js, tests/integration/index.test.js
Normally, I'd like to ask for code review, but I'd like to get this merged fast for a quick release as the issue was mainly caused by my forgetfulness 😊
=> Node is no longer a required interface

src/postgres/getCatalog.js
Addresses https://github.com/calebmer/postgraphql/issues/12
=> Cast a.attnum to int

docs/naming.md
In the gitter chat @intellix asked about why some of the decisions were made for names in PostGraphQL. I feel like this is something that a lot of people question, so here's some documentation for it!
@intellix and everyone else, feel free to challenge my assumptions and principles if you think there is a better fit for the product, I'm open to ideas 😉
(I also haven't edited/spell checked this yet so please be forgiving…)
=> Add naming warrants

docs/library.md, src/createServer.js, src/index.js, src/main.js, src/postgraphql.js, tests/createServer.test.js
Addresses #44. The current state of this PR is the simplest translation of what already exists to a simple interface. @grahamb, @hardchor what other things would you like to see in this interface?
I wrote a documentation article explaining how to use the new interface.
=> Add library usage

src/graphql/mutation/createDeleteMutationField.js, src/graphql/mutation/createInsertMutationField.js, src/graphql/mutation/createUpdateMutationField.js
Disregard if you want this solved a different way or just keep as is. ☺️ 
🖖
=> style(graphql): fix linting errors

examples/kitchen-sink/schema.sql, src/graphql/resolveProcedure.js, tests/integration/fixtures/procedure-mutation-with-array.graphql, tests/integration/fixtures/procedure-mutation-with-array.json, tests/integration/fixtures/procedure-query-with-array.graphql, tests/integration/fixtures/procedure-query-with-array.json
Just my first humble try on solving this. Currently only handles one-dimensional arrays. Maybe to naive, etc. Feedback very welcome.
=> fix(procedure): convert js arrays to postgres array type

package.json, src/createServer.js, tests/createServer.test.js
=> fix(server): throw error for bad auth header

src/graphql/createConnectionArgs.js, src/graphql/createConnectionType.js, src/graphql/mutation/createDeleteMutationField.js, src/graphql/mutation/createInsertMutationField.js, tests/integration/fixtures/mutation-delete.graphql, tests/integration/fixtures/mutation-delete.json, tests/integration/fixtures/mutation-insert.graphql, tests/integration/fixtures/mutation-insert.json
=> feat(graphql): add relay mutation types support

examples/forum/schema.sql
Took me a while to track this down when running this schema.
=> Remove emoji which causes "invalid byte sequence for encoding"

examples/forum/README.md
=> doc(example): add sample queries to forum example README

README.md, docs/anonymous-role.md, src/createServer.js, src/main.js, tests/createServer.test.js
@ferdinandsalis reminded me PostGraphQL currently doesn’t support anonymous roles, let’s fix that :blush:
=> Feature: add anonymous roles

docs/procedures.md
Fixed some broken links in the docs.
=> doc(procedures): Fix broken links in procedures.md

src/graphql/mutation/createInsertMutationField.js, tests/integration/fixtures/mutation-insert.graphql, tests/integration/fixtures/mutation-insert.json
Fixes https://github.com/calebmer/postgraphql/issues/117
=> Fix empty insert case

examples/kitchen-sink/schema.sql, src/graphql/mutation/createInsertMutationField.js, src/graphql/mutation/createUpdateMutationField.js, tests/integration/fixtures/mutation-insert.graphql, tests/integration/fixtures/mutation-insert.json
Fixes https://github.com/calebmer/postgraphql/issues/116
=> Fix insert false bug

CONTRIBUTING.md, scripts/run-kitchen-sink-sql
@calebmer I made these tweaks following your early merge of #197 (thanks for doing that!)
By the way, the `Types.money` tests are still failing for me; still haven't had a chance to dig in and figure out why. All the other tests are running well now though, thanks to the increased timeouts.
=> fix(contributing): minor corrections

package.json, src/graphql/schema/__tests__/createMutationGqlField-test.js, src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationOperations-test.js.snap, src/postgraphql/__tests__/fixtures/queries/dynamic-json.graphql
Most important is `null` value in language and in variables
[Show all commits since 0.7.1](https://github.com/graphql/graphql-js/compare/v0.7.1...master)
=> GraphQL-js next (will be 0.8)

README.md
=> feat(docs): add to readme a link to contributing

README.md
I think this readme gives perfect introduction to postgraphql with JWT so it worth having direct link from  project top-level readme.
=> Adding link to forum sample tutorial from top level readme

examples/forum/TUTORIAL.md
Thanks for the tutorial, just had a run-through now. Interesting project!
=> Minor typos in TUTORIAL.md

src/README.md
Hopefully helps developers get started faster, e.g. #334
=> Link to CONTRIBUTING from src/README

src/postgraphql/withPostGraphQLContext.ts
Removes the `explain analyse` functionality from the Postgres debugger. I never liked how it was enabled with `DEBUG=postgraphql*` as it is bad for production apps who may use that debugging statement for logs by executing a side effect. As it turns out this side effect could cause mutations to be run twice which is something we _never_ want to happen (see https://github.com/calebmer/postgraphql/issues/350#issuecomment-279177585).
The feature is more troublesome than useful. It is easy enough to copy-paste a SQL statement from the debug logs into `psql` and explain/analyse there.
=> Remove explain from client

src/postgraphql/cli.ts
=> Emit listen port during startup

README.md
I gave a talk on PostGraphQL at GraphQL Summit which I am pretty proud of, so we should probably add that to the readme.
Also, PostGraphQL has a pretty advanced watch mode that provides the best GraphQL API development experience in the entire GraphQL ecosystem. We should probably mention that 😉
=> Add video and add section about watch mode

docs/library.md
I spent quite some time looking for this. I thought it'd be useful to have it in the documentation.
=> docs(library): document pgSettings option

src/__tests__/utils/printSchemaOrdered.js, src/postgraphql/__tests__/__snapshots__/postgraphqlIntegrationSchema-test.js.snap, src/postgraphql/__tests__/postgraphqlIntegrationSchema-test.js
In preparation for v4 this will make it easier to determine how close the generated schemas are.
=> chore(test): alphabetically order schema in snapshots

package.json
Implementing best practices in advance of a new v3 release.
=> chore(package): optimise npm publish

TROUBLESHOOTING.md
Ref: https://github.com/postgraphql/postgraphql/issues/529
=> docs(TROUBLESHOOTING): stored procedures not appearing

package.json, src/__tests__/utils/kitchenSinkSchemaSql.ts, src/postgraphql/watch/watchPgSchemas.ts, src/postgres/introspection/introspectDatabase.ts, src/postgres/utils/sql.ts, typings/pg-minify.d.ts
* Use pg-minify [according to its API](https://github.com/vitaly-t/pg-minify/tree/master/typescript)
* Use the TypeScript declarations that come with pg-minify (removing local re-declaration)
=> correcting pg-minify usage.

docs/library.md
As this applies to both Relay Classic and Relay Modern.
=> Removing mention of Relay 1

docs/library.md, src/postgraphql/http/__tests__/createPostGraphQLHttpRequestHandler-test.js, src/postgraphql/http/createPostGraphQLHttpRequestHandler.js, src/postgraphql/postgraphql.ts
I hope this gets merged to v4 soon, which I prefer to use rather than v3, due to better SQL queries v4 generates on average 😄
=> v3 `pgSettings` function

examples/forum/TUTORIAL.md
"twice as long as a tweet" => "as long as a tweet" (totes crazy)
=> Update TUTORIAL.md (outdated phrase)

examples/forum/TUTORIAL.md
`GRANT` is not restricted to tables.
=> chore(docs): Improve narrative on grants

SPONSORS.md
**A huge thanks to my current sponsors** 🙏 
If you or your company can afford to sponsor my work on PostGraphQL/PostGraphile I'd really appreciate it!
Sponsorship will enable me to get version 4 out sooner. Once that is done, sponsorship can help me build the other features people are excited about having added - most significantly subscriptions support - more rapidly! And of course it covers ongoing maintenance, responding to issues, fixing any security issues that may come up, and everything else a project maintainer must handle.
Please support my work via Patreon:
https://www.patreon.com/benjie
=> docs(SPONSORS): Add SPONSORS.md file

README.md, docs/default-role.md, docs/library.md, examples/README.md
definetly -> definitely 
priveleges -> privileges 
verifing-> verifying
=> corrected typos in docs

.vscode/settings.json, src/postgraphql/http/createPostGraphQLHttpRequestHandler.d.ts, src/postgraphql/postgraphql.ts, src/postgraphql/schema/exportPostGraphQLSchema.ts, src/postgraphql/withPostGraphQLContext.ts, src/postgres/inventory/pgClientFromContext.ts, tslint.json
normalize spacing before function parens
=> fix function linting

src/postgraphile/cli.ts
=> feat(cluster): introduce cluster feature

TROUBLESHOOTING.md
as per #670  , added troubleshooting for anyone having issues with JWTs when using postgraphile as a library.
Can't remember what else we discussed, but I think this was the crux of it.
=> closes #670 - adds troubleshooting information for using jwts

src/postgraphile/postgraphile.ts
Also re-orders the options so they line up with the CLI options.
=> docs(library): add comments to the library options to be put into docs

package.json, yarn.lock
Fixes JWT issue referenced in #708
=> fix(sql): remove unnecessary row expansion

src/index.ts, src/postgraphile/cli.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.d.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.js, src/postgraphile/pluginHook.ts, src/postgraphile/postgraphile.ts, src/postgraphile/withPostGraphileContext.ts, typings/pg.d.ts
⚠️  Experimental
Plugins can add CLI options and hook into various other parts of the system. This'll probably expand over time.
This interface is liable to change; it remains undocumented and as such changes to it are deemed non-breaking.
=> feat(plugins): plugins for non-GraphQL parts

src/postgraphile/cli.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.js, src/postgraphile/postgraphile.ts, src/postgraphile/withPostGraphileContext.ts
Fixes https://github.com/graphile/postgraphile/pull/734
=> feat(middleware): batched queries support

src/postgraphile/http/createPostGraphileHttpRequestHandler.js
Previously if you had `bodyParser` in your Koa middleware stack before PostGraphile, e.g.
```js
const Koa = require('koa');
const bodyParser = require('koa-bodyparser');
const { postgraphile } = require('postgraphile');
const app = new Koa();
app.use(bodyParser()); // < this!
app.use(postgraphile());
app.listen(3000);
```
then PostGraphile (well, strictly it was `body-parser` itself) would hang whilst processing GraphQL requests because it didn't realise that the request body had already been consumed.
I've added some additional middleware which converts the Koa body parsing over to something that looks like Connect body parsing (it has to manipulate the `ctx.req` object to achieve this - sorry!); this should solve this issue.
Remember: Koa support is experimental! When raising issues …
=> fix(koa): don't hang when body is already parsed

src/postgraphile/http/createPostGraphileHttpRequestHandler.js
Avoids "Cannot set headers after they are sent to the client" error by
not ending the request from within PostGraphile, instead letting Koa
handle that.
=> fix(koa): let Koa finalise the request

src/postgraphile/http/createPostGraphileHttpRequestHandler.js, src/postgraphile/http/setupServerSentEvents.js
=> fix(koa): support server-sent events in Koa

src/postgraphile/__tests__/withPostGraphileContext-test.js, src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js, src/postgraphile/withPostGraphileContext.ts
=> fix(jwt): allow booleans in JWTs again

SPONSORS.md
Updated Sponsors list to reflect July's Patrons.
=> sponsorship: update sponsors for July 🙏

src/__tests__/utils/pgPool.ts, src/__tests__/utils/withPgClient.ts, src/interfaces.ts, src/postgraphile/cli.ts, src/postgraphile/extendedFormatError.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts, src/postgraphile/postgraphile.ts, src/postgraphile/schema/exportPostGraphileSchema.ts, src/postgraphile/withPostGraphileContext.ts, tslint.json
With some heavy overrides to avoid having to rewrite too much code.
=> chore(lint): use `tslint:latest`

SPONSORS.md
Needs double checking, don't merge just yet.
=> sponsorship: update sponsors for August 🙏

src/postgraphile/__tests__/withPostGraphileContext-test.js, src/postgraphile/withPostGraphileContext.ts
for issue: https://github.com/graphile/graphile-build/issues/266
withPostGraphileContext will have callback in form of:
`
{
pgClient,
pgRole,
jwtClaims
}
`
=> feat(jwt): include JWT claims in withPostGraphileContext callback

src/interfaces.ts, src/postgraphile/cli.ts, src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
=> fix(bodySizeLimit): Extend body size limit to other parsers

TROUBLESHOOTING.md
=> docs(TROUBLESHOOTING): add instructions to file

examples/forum/TUTORIAL.md, examples/forum/schema.sql
=> docs(TUTORIAL): use missing_ok parameter

src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
=> fix(cors): fix allowed methods header, allow X-Apollo-Tracing

src/postgraphile/cli.ts
=> style(cli): neaten up the PostGraphile messages

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
Fixes https://github.com/graphile/postgraphile/issues/851
=> fix(cache): estimate memory usage more accurately

src/interfaces.ts, src/postgraphile/cli.ts
=> Document skipPlugins and expose CLI option

SPONSORS.md
🙏 Thanks to all sponsors for helping to keep Postgraphile going 🙏
=> sponsorship: update sponsors for October 🙏

src/postgraphile/withPostGraphileContext.ts
Added debug notice in withPostGraphileContext, to print notice logs with Postgres procedures
Closes #607
=> Added debug notice

src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
=> feat(errors): improve server-side message when JWT expired

examples/forum/TUTORIAL.md
=> fix(examples): Successfully

src/postgraphile/cli.ts
- Add link to PostgreSQL's documentation on environment variables
=> docs(postgraphile): environment variable link

postgraphiql/src/components/PostGraphiQL.js, postgraphiql/src/components/postgraphiql.css
=> feat(graphiql): minor tweaks

prettier.config.js, src/interfaces.ts, src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
To avoid it being a breaking change.
=> fix(http): absolute route parsing is now opt-in

SPONSORS.md
🙏 Thanks to all sponsors for helping to keep Postgraphile going 🙏
=> sponsorship: update sponsors for November 🙏

src/interfaces.ts
=> fix(ignoreIndexes): add to interfaces

postgraphiql/package.json, postgraphiql/yarn.lock
Fixes #908 by using my fork of GraphiQL including this fix: https://github.com/graphql/graphiql/pull/747
=> fix(graphiql): solve favoriting issue

package.json, yarn.lock
Adds support for smart-comment definition of relations, primary keys, etc (e.g. opens these up to views/materialized views).
=> feat(deps): upgrade postgraphile-core

SPONSORS.md
🙏 Thanks to all sponsors for helping to keep Postgraphile going 🙏
=> sponsorship: update sponsors for January 🙏

src/postgraphile/cli.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts, src/postgraphile/pluginHook.ts
=> feat(hooks): add hooks for HTTP results

SPONSORS.md
🙏 Thanks to all sponsors for helping to keep Postgraphile going 🙏
=> sponsorship: update sponsors for February 🙏

SPONSORS.md
=> sponsorship: update sponsors for March 🙏

package.json, yarn.lock
Fix issue with connections over-fetching.
=> fix(deps): upgrade postgraphile-core

SPONSORS.md
=> sponsorship: update sponsors for April 🙏

postgraphiql/package.json, postgraphiql/yarn.lock
=> fix(deps): upgrade GraphiQL

src/index.ts, src/interfaces.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts, src/postgraphile/http/subscriptions.ts, src/postgraphile/postgraphile.ts
Fixes https://github.com/graphile/graphile-engine/pull/435
=> fix(ts): replace 'export *' with explicit exports to allow declaration merging

src/postgraphile/postgraphile.ts
=> fix(resilience): don't exit on initial schema build fail

package.json, postgraphile, postgraphiql/package.json, postgraphiql/yarn.lock, scripts/dev, src/postgraphile/cli.ts, tsconfig.json
This time GraphiQL related. (Also fix dev mode.)
=> chore(deps): Upgrade more dependencies

SPONSORS.md
=> sponsorship: update sponsors for May 🙏

SPONSORS.md
Sponsors file update for August, thank you folks 🙏
=> Sponsors file update for August, thank you folks 🙏

src/interfaces.ts
Fixes https://github.com/graphile/postgraphile/issues/1128
=> fix(docs): clarify jwtRole is path components (not possible roles)

src/postgraphile/http/__tests__/createPostGraphileHttpRequestHandler-test.js, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts
=> fix: make sure x-graphql-event-stream url is domain relative

package.json, rmlocal.sh, src/postgraphile/__tests__/__snapshots__/postgraphileIntegrationSchemaExport-test.js.snap, yarn.lock
=> chore(types): remove @types/graphql

SPONSORS.md
=> sponsorship: Update for September, thank you all 🙏

CONTRIBUTING.md
=> Document test database setup

README.md
Many thanks to our four Featured Sponsors 😁💙
=> sponsorship: add Storyscript and Point72 as featured sponsors

SPONSORS.md
=> sponsorship: Update for October & November, thank you 🙏

README.md
Thank you to all our Featured Sponsors, past and present, for supporting our work 🤩
=> Update README.md for sponsorship update

postgraphiql/src/components/PostGraphiQL.js, postgraphiql/src/components/postgraphiql.css, postgraphiql/src/formatSQL.js, src/interfaces.ts, src/postgraphile/cli.ts, src/postgraphile/http/createPostGraphileHttpRequestHandler.ts, src/postgraphile/postgraphile.ts, src/postgraphile/withPostGraphileContext.ts
=> feat(graphiql): add 'explain' button

src/postgraphile/schema/exportPostGraphileSchema.ts
=> fix(export): only write schema if it differs

CONTRIBUTING.md
=> doc(CONTRIBUTING): link to docker instructions in wiki

SPONSORS.md
Thank you to all our sponsors for December.
=> sponsorship: Update for December, thank you

src/interfaces.ts
Fixes https://github.com/graphile/graphile-engine/issues/592
=> docs: note a couple more middleware-only options

package.json, yarn.lock
Mostly this: https://github.com/graphile/graphile-engine/pull/594
=> feat(deps): upgrade graphile engine

SPONSORS.md
Thank you to all our sponsors for the New Year 🙌
=> sponsorship: Update for Jan and Feb, thank you

SPONSORS.md
Thank you to all our sponsors for Spring 🙌 And a very warm welcome to our new featured sponsor, Postlight 💙
=> sponsorship: Update for March

postgraphiql/src/index.css
=> fix(graphiql): fix icon alignment issue

src/index.ts, src/postgraphile/index.ts, src/postgraphile/withPostGraphileContext.ts
=> feat: export debugPgClient

package.json, yarn.lock
Updates to the latest release of postgraphile-core/graphile-utils
Ever-so-slight improvement when dealing with intervals.
None known.
=> chore: upgrade postgraphile-core

src/postgraphile/http/subscriptions.ts
Fixes https://github.com/graphile/postgraphile/pull/1361#discussion_r513757123
Negligible.
None
=> fix: remove optional chaining

src/postgraphile/http/frameworks.ts
Fix a lint issue which popped up while I was working on #1396. The lint check seems to be passing in CI without this change, so I'm a bit puzzled why running the lint fix locally is finding it.
None
None
=> chore(ts): remove type declarations that can be implied

src/postgraphile/http/frameworks.ts
Subtle type mod to give users more flexibility.
None.
None.
=> fix(types): use interface to enable declaration merging

src/postgraphile/http/liveSubscribe.ts, src/postgraphile/http/subscriptions.ts
Intention is to make #725 simpler.
Negligible.
None.
=> chore: give liveSubscribe access to options/pluginHook

src/interfaces.ts
Type only fix; not sure why it was added here but it's not needed (and putting it here as required was a breaking change).
Fixes #1491 
None.
None.
=> fix(types): WithPostGraphileContextOptions doesn't need shutdownActions

README.md
Tiny fix to the Sponsor's Table in the readme, stops the images getting squished in narrow browsers. Thank you to all our sponsors, past and present, your donations help us to keep working on free and open source software 😍
=> fix(README): formatting

README.md, SPONSORS.md, sponsors.json
Thank you everyone for your continued sponsorship 🤩
=> sponsorship: update sponsors 🙏

README.md
=> docs: add PostGraphile V5 message to README

README.md
=> PostGraphile V5 is in beta

.changeset/early-tables-admire.md, graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts, graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts
Fixes https://github.com/graphile/graphile-engine/pull/808
=> Support scalars via resolvers in makeExtendSchemaPlugin

.changeset/small-planes-jam.md, graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts
Fixes https://github.com/benjie/ouch-my-finger/pull/8
=> Fix forbidden early interfaces evaluation

.changeset/olive-tomatoes-play.md, graphile-build/graphile-build-pg/src/plugins/PgRefsPlugin.ts
Fixes https://github.com/graphile/crystal/issues/1749
=> Fix error message when ref is used with no FK

.changeset/green-owls-cry.md, grafast/grafast/src/engine/OperationPlan.ts, grafast/grafast/src/engine/StepTracker.ts, postgraphile/postgraphile/__tests__/queries/polymorphic/single-table-items-and-children.json5, postgraphile/postgraphile/__tests__/queries/polymorphic/single-table-items-and-children.mermaid, postgraphile/postgraphile/__tests__/queries/polymorphic/single-table-items-and-children.sql, postgraphile/postgraphile/__tests__/queries/polymorphic/single-table-items-and-children.test.graphql
Discovered this issue by accident; need to dig into it to find out why it's happening but this patch should work around it without major issues.
=> Fix a polymorphic planning issue

.changeset/spotty-cougars-marry.md, grafast/grafserv/src/core/base.ts, grafast/grafserv/src/middleware/graphql.ts, grafast/grafserv/src/utils.ts
This is a migration of https://github.com/graphile/crystal-pre-merge/pull/491 to this repository. All thanks for the work to @Dodobibi :raised_hands:
=> Send GraphQLError to client

grafast/grafast/src/interfaces.ts
https://github.com/graphile/crystal/pull/1777#discussion_r1344317545
=> Clarified docs re extending RequestContext for specific servers

grafast/grafserv/src/servers/fastify/v4/index.ts, grafast/grafserv/src/servers/h3/v1/index.ts, grafast/grafserv/src/servers/koa/v2/index.ts, grafast/grafserv/src/servers/node/index.ts
=> 501 is the correct “not implemented” status code

.changeset/wicked-meals-flow.md, grafast/dataplan-pg/src/codecs.ts, graphile-build/graphile-build-pg/src/plugins/PgCodecsPlugin.ts
=> Fix missing tags on enum codecs

.changeset/funny-crews-raise.md, grafast/grafserv/package.json
I forgot to export the lambda server
=> Export lambda server

grafast/website/grafast/index.mdx
fix `users and friends example` broken link
=> Fix users and friends link in the documentation

utils/graphile-config/src/hooks.ts
=> We don't need plugins to be mutable

postgraphile/website/postgraphile/make-add-pg-table-order-by-plugin.md
=> include helper in example

postgraphile/website/postgraphile/polymorphism.md
Fixing a missing documentation on polymorphic. Discussion is [here](https://discord.com/channels/489127045289476126/953710447087980654/1174665143024627743).
=> Doc update on polymorphic views

.changeset/red-swans-sing.md, .changeset/thirty-ants-admire.md, grafast/grafast/src/steps/node.ts, graphile-build/graphile-build-pg/src/plugins/PgPolymorphismPlugin.ts, graphile-build/graphile-build/src/plugins/AddNodeInterfaceToSuitableTypesPlugin.ts, graphile-build/graphile-build/src/plugins/NodePlugin.ts, graphile-build/graphile-utils/tsconfig.json, postgraphile/postgraphile/graphile.config.ts, postgraphile/postgraphile/src/plugins/PgV4SimpleSubscriptionsPlugin.ts, postgraphile/postgraphile/src/presets/v4.ts, postgraphile/postgraphile/tsconfig.build.json
Fixes [#1861](https://github.com/graphile/crystal/issues/1861)
=> Add emulation of `simpleSubscriptions: true` to V4 preset

postgraphile/website/postgraphile/community-plugins.md
=> Fix broken link

postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.subscriptions.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/foreignKey-smart-tag-autofix.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/foreignKey-smart-tag-good.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/function-clash-with-tags-file-workaround.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/function-clash.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/indexes.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/inflect-core.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/noDefaultMutations.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/rbac.ignore.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/relay1.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/simple-collections.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/simple-collections.only.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/simplePrint.graphql, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.1.graphql, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.graphql
=> Test computed column function comments

.changeset/strange-hats-help.md, utils/pg-introspection/src/introspection.ts
=> Import latest PG16 docs into pg-introspection

.changeset/late-news-sniff.md, grafast/dataplan-pg/src/steps/pgSelectSingle.ts, postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/queries/polymorphic/returns-setof.json5, postgraphile/postgraphile/__tests__/queries/polymorphic/returns-setof.mermaid, postgraphile/postgraphile/__tests__/queries/polymorphic/returns-setof.sql, postgraphile/postgraphile/__tests__/queries/polymorphic/returns-setof.test.graphql, postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.graphql, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql
=> Fix aggregates over polymorphic connections

.changeset/small-shirts-prove.md, graphile-build/graphile-build-pg/src/plugins/PgRefsPlugin.ts, graphile-build/graphile-build-pg/src/plugins/PgRelationsPlugin.ts, postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/schema/v4/refs.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/refs.test.ts, postgraphile/website/postgraphile/refs.md
Fixes #1889 
Negligible.
None known.
=> Add pgRefDetails to scope for some ref-related fields

postgraphile/website/postgraphile/exporting-schema.md
Better than nothing :man_shrugging:
=> Add example of running exported schema

.changeset/tough-swans-juggle.md, postgraphile/postgraphile/src/presets/lazy-jwt.ts
Fixes #1847
Negligible.
None known.
=> Return 401 status when JWT validation fails

.changeset/tough-cheetahs-develop.md, utils/graphile-config/src/index.ts, utils/graphile-config/src/resolvePresets.ts
Fixes #1842 
Negligible.
None known.
=> Prevent using appendPlugins/prependPlugins/skipPlugins in presets

.changeset/red-jobs-deny.md, grafast/grafserv/src/index.ts
Fixes #1936 
Negligible.
None known.
=> Export 'defaultMaskError' from grafserv

utils/pg-introspection/README.md
=> fix: variable typo

.changeset/many-donkeys-teach.md, grafast/dataplan-pg/__tests__/queries/connections/pagination-after.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-after.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-end-last.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-end-last.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-end.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-end.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-last-pagination-only.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-last-pagination-only.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-last.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before-last.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/connections/pagination-before.mermaid, grafast/dataplan-pg/src/steps/pgSelect.ts, postgraphile/postgraphile/__tests__/queries/polymorphic/person-log-entries.after-caroline.mermaid, postgraphile/postgraphile/__tests__/queries/v4/connections-blankcursor.mermaid, postgraphile/postgraphile/__tests__/queries/v4/connections.boolean.json5, postgraphile/postgraphile/__tests__/queries/v4/connections.boolean.mermaid, postgraphile/postgraphile/__tests__/queries/v4/connections.boolean.sql, postgraphile/postgraphile/__tests__/queries/v4/connections.boolean.test.graphql, postgraphile/postgraphile/__tests__/queries/v4/connections.mermaid, postgraphile/postgraphile/__tests__/queries/v4/connections.sql
Fixes #1942; and probably some other issues!
Marginal improvement.
None known.
=> Fix double-encoding of queryValues in cursors

postgraphile/website/postgraphile/make-extend-schema-plugin.md, postgraphile/website/postgraphile/migrating-from-v4/index.mdx, postgraphile/website/postgraphile/migrating-from-v4/make-extend-schema-plugin.md, postgraphile/website/postgraphile/migrating-from-v4/migrating-custom-plugins.md, postgraphile/website/postgraphile/polymorphism.md, postgraphile/website/postgraphile/subscriptions.md, postgraphile/website/postgraphile/usage-library.md
Grafast is in open beta :partying_face:
We don't need the little tooltip telling you how to get into the Grafast website any more
=> postgraphile website: Remove helping2test

grafast/website/grafast/step-library/standard-steps/loadOne.md
fixes incorrect type in documentation
N/A
N/A
=> correct type defined in documentation

.changeset/witty-windows-hang.md, grafast/grafast/src/steps/load.ts
=> Don't warn that Load uses non-async execute function

.changeset/chilly-shoes-wonder.md, grafast/grafast/src/step.ts
Fixes #1966
Trivial improvement in production in some circumstances during planning.
None known (potentially reduce a DoS possibility through triggering excessive logging?)
=> Don't output non-async function warning in production

grafast/grafast/src/engine/LayerPlan.ts, grafast/grafast/src/engine/executeBucket.ts
Discovered whilst working on a different feature; fixes bugs introduced in #1973 
Negligible.
Fixes.
=> Fix bugs in unary step logic

grafast/grafast/__tests__/basic-interface-test.ts
@devunt raised #1976 but there was insufficient information to reproduce the issue. I've attempted to reproduce it three different ways but all the tests I've written are passing :man_shrugging:
If someone can demonstrate it failing in the test I'd be happy to have a go at fixing it.
=> Fixes #1976: cannot reproduce issue

grafast/website/src/pages/sponsor.mdx, postgraphile/website/src/pages/sponsor.mdx
One more sponsor update for this repo: update to the featured sponsors on postgraphile.org and grafast.org
Thank you to all our sponsors, past and present :sparkling_heart:
=> websites: Sponsor update

postgraphile/website/postgraphile/behavior.md
Relates to https://github.com/graphile/pg-aggregates/pull/67
=> Add documentation for the behaviors for aggregates

.changeset/quick-dogs-clap.md, .changeset/silent-cups-allow.md, graphile-build/graphile-utils/src/makeWrapPlansPlugin.ts, postgraphile/postgraphile/graphile.config.ts, utils/graphile-export/src/exportSchema.ts
=> Export wrap

grafast/grafast/src/engine/OutputPlan.ts
Guess it missed some refactoring
=> Fix layerPlanId -> layerPlan.id

.changeset/early-toes-walk.md, grafast/grafast/__tests__/errorHandling-test.ts, grafast/grafast/src/engine/executeBucket.ts
Fixes https://github.com/benjie/ouch-my-finger/pull/14
None known.
None known.
=> Fix bug in side effect handling leading to additional dependency being added

.changeset/weak-llamas-thank.md, grafast/grafast/package.json, grafast/ruru-components/package.json, yarn.lock
=> Due to middleware, graphile-config is required by grafast

postgraphile/website/src/pages/sponsor.mdx
An update to the website with our current featured sponsors, thank you to all sponsors past and present 🤩
NA
NA
=> Update to sponsors

grafast/website/src/pages/sponsor.mdx
Featured sponsor update for Grafast, thank you to all our sponsors 🤩
NA
NA
=> Sponsor page for Grafast updated

grafast/website/grafast/step-library/standard-steps/loadMany.md, grafast/website/grafast/step-library/standard-steps/loadOne.md
=> Overhaul loadOne docs

.changeset/large-cameras-listen.md, grafast/dataplan-pg/src/steps/pgSelectSingle.ts
=> Broaden types on pgSelectSingleFromRecord

.changeset/mighty-jars-cover.md, grafast/grafast/src/graphqlCollectFields.ts
=> Add more evalable directive types

.changeset/chatty-roses-deliver.md, grafast/grafast/src/step.ts
=> Throw earlier error when adding dependency from deeper layer plan

.changeset/tame-trainers-smoke.md, graphile-build/graphile-build-pg/src/plugins/PgCustomTypeFieldPlugin.ts, postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.subscriptions.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/defaultOptions.subscriptions.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/function-clash-with-tags-file-workaround.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/function-clash-with-tags-file-workaround.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/function-clash.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/function-clash.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/indexes.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/indexes.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/inflect-core.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/inflect-core.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/rbac.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/rbac.ignore.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/rbac.ignore.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/simplePrint.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/simplePrint.graphql, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.1.graphql, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.graphql
=> Fix @NotNull to apply to payload field, not payload type

.changeset/beige-cherries-call.md, graphile-build/graphile-build-pg/src/plugins/PgCustomTypeFieldPlugin.ts, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.1.graphql
=> Add V5 support for @resultFieldName

.github/workflows/test-base.yml, .github/workflows/test.yml, CONTRIBUTING.md, grafast/dataplan-pg/__tests__/helpers.ts, grafast/dataplan-pg/__tests__/sharedHelpers.ts, grafast/dataplan-pg/package.json, grafast/dataplan-pg/scripts/runExampleSchema.mjs, grafast/dataplan-pg/serve-example-schema.js, graphile-build/graphile-build-pg/package.json, graphile-build/graphile-utils/__tests__/RegisterUserPlugin.test.ts, graphile-build/graphile-utils/__tests__/makeAddPgTableConditionPlugin.test.ts, graphile-build/graphile-utils/__tests__/makeAddPgTableOrderByPlugin.test.ts, graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts, graphile-build/graphile-utils/package.json, package.json, postgraphile/postgraphile/__tests__/helpers.ts, postgraphile/postgraphile/jest.config.cjs, postgraphile/postgraphile/package.json, scripts/pretest, utils/jest-serializer-graphql-schema/package.json, utils/lru/package.json, utils/pg-sql2/package.json, utils/tamedevil/package.json
Massive test performance improvement
=> Overhaul tests to run in parallel and use template database

.changeset/funny-mayflies-count.md, .changeset/gold-windows-matter.md, .changeset/metal-moose-perform.md, grafast/bench/benchmarks/dataplan-pg-example/graphile.config.ts, grafast/grafast/src/engine/OperationPlan.ts, grafast/grafast/src/index.ts, graphile-build/graphile-build-pg/src/examples/NO_DATA_GATHERING.ts, graphile-build/graphile-build-pg/src/examples/benjies-test-script.ts, postgraphile/pgl/README.md, postgraphile/pgl/graphile.config.ts, postgraphile/postgraphile/graphile.config.ts, utils/graphile-config/src/index.ts
=> A few really minor tweaks across the codebase

postgraphile/website/postgraphile/inflection.md, postgraphile/website/postgraphile/registry.md, postgraphile/website/postgraphile/usage-library.md
=> Minor documentation fixes

postgraphile/website/postgraphile/inflection.md, postgraphile/website/postgraphile/registry.md, postgraphile/website/postgraphile/usage-library.md
Small fixes to the docs as I go through them
=> Docs fixes

utils/website/graphile-config/middleware.md
=> Add documentation for Graphile Config middleware

CONTRIBUTING.md, graphile-build/graphile-utils/README.md
Extracted from #2258 thanks to @kzlar.
=> Updated docs for testers

.changeset/lemon-lamps-float.md, graphile-build/graphile-simplify-inflection/README.md
According to my testing, this comment was incorrect. I think this is correct, now?
The correction also aligns with @benjie's advice on discord:
https://discord.com/channels/489127045289476126/1325590053929484292/1325594053034901564
=> Correct the pgShortPk comment in the README

.eslintignore, .gitignore, grafast/dataplan-pg/__tests__/helpers.ts, grafast/dataplan-pg/__tests__/queries/relations/basics.test.graphql, graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts, package.json
=> Minor housekeeping changes

postgraphile/postgraphile/package.json
=> Do not update snapshots in export mode

grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.deopt.mermaid, grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.deopt.sql, grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.json5, grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.mermaid, grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.sql, grafast/dataplan-pg/__tests__/queries/conditions/archived-forum-inherited-messages.stream-7.test.graphql, grafast/grafast/src/engine/OperationPlan.ts
Just to make sure it works! I've also added notes about how it _should_ work when we support the new stream/defer.
=> Add test of stream next to no-stream

CONTRIBUTING.md, postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/queries/polymorphic/vulns-ordering.json5, postgraphile/postgraphile/__tests__/queries/polymorphic/vulns-ordering.mermaid, postgraphile/postgraphile/__tests__/queries/polymorphic/vulns-ordering.sql, postgraphile/postgraphile/__tests__/queries/polymorphic/vulns-ordering.test.graphql, postgraphile/postgraphile/__tests__/schema/v4/polymorphic-auto-add-types.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/polymorphic-auto-add-types.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/polymorphic.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/skipNodePlugin.polymorphic.1.graphql, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v5/skipNodePlugin.polymorphic.1.graphql
- Test added for more coverage of ordering in interfaces
- Checking for expected behaviour of computed columns in tables with interfaces
- Added snapshot instructions to contributing file
=> test: postgraphile tests for interface ordering and interface computed columns

postgraphile/postgraphile/__tests__/queries/v4/json-nested-query.json5, postgraphile/postgraphile/__tests__/queries/v4/json-nested-query.mermaid, postgraphile/postgraphile/__tests__/queries/v4/json-nested-query.sql, postgraphile/postgraphile/__tests__/queries/v4/json-nested-query.test.graphql
Much needed test to make sure variables in nested json go through planning correctly.
=> Test for variable in nested json

grafast/grafast/__tests__/makeGrafastSchema-test.ts
=> Check that creating a schema with input object works

.changeset/brave-teachers-study.md, .changeset/silent-lemons-fetch.md, .changeset/tall-pots-check.md, grafast/bench/src/index.ts, grafast/dataplan-pg/src/examples/exampleSchema.ts, grafast/dataplan-pg/src/steps/pgSelect.ts, grafast/dataplan-pg/src/steps/pgValidateParsedCursor.ts, grafast/grafast/src/engine/OperationPlan.ts, grafast/grafast/src/engine/executeBucket.ts, grafast/grafast/src/input.ts, grafast/grafast/src/interfaces.ts, grafast/grafast/src/steps/constant.ts
Spent the day reviewing, here's some more things I spotted...
=> More tweaks from code review

postgraphile/website/postgraphile/usage-library.md
Add two complete examples.  First example is using JavaScript with the entire server in one file.  The second example uses TypeScript and separates the configuration from the server
=> Add complete JavaScript and TypeScript examples

.changeset/angry-pillows-fold.md, grafast/grafast/src/engine/OperationPlan.ts
Oops, we were only checking that the flags matched on the first dependency!
=> Fix a bug in deduplication

.changeset/stupid-lemons-add.md, grafast/grafast/src/engine/OperationPlan.ts, graphile-build/graphile-utils/__tests__/PolymorphicSideEffects.test.ts, graphile-build/graphile-utils/__tests__/utils-schema.sql
Fixes https://github.com/benjie/ouch-my-finger/pull/21
Increases memory allocation/garbage collection and computation during plan finalization, but unlikely to be a large impact.
None known.
=> Fix issue with unary side effect steps in polymorphic positions

.changeset/shaggy-streets-start.md, utils/pg-sql2/src/index.ts
=> pg-sql2 isEquivalent doesn't need mutable map

postgraphile/website/src/components/WarningSection/index.js, postgraphile/website/src/components/WarningSection/styles.module.css, postgraphile/website/src/pages/index.js, postgraphile/website/src/pages/v5beta.mdx, postgraphile/website/src/pages/v5beta.module.css
Check out the neat progress bar: 
Check all the copy!
=> website: a V5 progress page

grafast/website/src/pages/sponsor.mdx, postgraphile/website/src/pages/sponsor.mdx
Sponsors update for PostGraphile and Grafast websites, thank you to all past and present sponsors! 💖
=> websites: Update sponsor page

.changeset/fluffy-mice-lay.md, grafast/grafast/src/steps/load.ts
Surprised we didn't already do this...
=> Implement deduplication of Load steps

grafast/grafast/src/steps/__trackedValue.ts, postgraphile/postgraphile/__tests__/queries/v4/connections.variables.mermaid, postgraphile/postgraphile/__tests__/queries/v4/nodeId-earlyExit.mermaid
=> Cache variables in input steps

grafast/website/grafast/polymorphism.mdx
Editorial and added diagrams to the new polymorphism page
=> add to polymorphism docs

grafast/website/grafast/step-library/standard-steps/coalesce.md
=> Document coalesce

grafast/grafast/__tests__/planningErrors-test.ts, grafast/grafast/src/engine/OperationPlan.ts, grafast/grafast/src/engine/OperationPlanTypes.ts, grafast/grafast/src/engine/OutputPlan.ts
Added tests for this, behavior is improved versus previous behavior.
=> Catch planning errors in various positions

.changeset/tall-experts-talk.md, grafast/dataplan-pg/package.json, grafast/ruru-components/src/ruru.tsx, grafast/ruru/package.json, grafast/ruru/webpack.config.ts, yarn.lock
(Also fixes warning in GraphiQL rendering.)
=> chore: upgrade webpack

.changeset/wicked-tools-matter.md, graphile-build/graphile-build-pg/src/plugins/PgTableNodePlugin.ts
Noticed this whilst reviewing #2639
=> Only allow one resource

grafast/grafast/__tests__/dcc/dcc-schema.ts, grafast/grafast/__tests__/dcc/dcc-types.ts, grafast/grafast/__tests__/dcc/queries-test.ts, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection-page2.json5, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection-page2.test.graphql, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection-reverse.json5, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection-reverse.test.graphql, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection.json5, grafast/grafast/__tests__/dcc/queries/active-crawler-items-connection.test.graphql, grafast/grafast/__tests__/dcc/queries/friends-connection-before-after.errors.json5, grafast/grafast/__tests__/dcc/queries/friends-connection-before-after.json5, grafast/grafast/__tests__/dcc/queries/friends-connection-before-after.test.graphql, grafast/grafast/__tests__/dcc/queries/friends-connection.json5, grafast/grafast/__tests__/dcc/queries/friends-connection.test.graphql, grafast/grafast/src/steps/connection.ts
Some tests for
#2659 
- Better error given for connections when using eg first & before
=> connections: grafast connection tests

grafast/website/grafserv/servers/hono.md
`server` wasn't defined; `app` was meant.
=> Improve hono docs

postgraphile/website/postgraphile/requirements.md
=> intervalstyle can change

.changeset/smooth-things-wait.md, grafast/dataplan-pg/package.json, grafast/grafast/package.json, grafast/grafserv/package.json, grafast/ruru-components/package.json, grafast/ruru/package.json, graphile-build/graphile-build-pg/package.json, graphile-build/graphile-build/package.json, graphile-build/graphile-utils/package.json, postgraphile/postgraphile/package.json, scripts/benjies-depcheck.mjs, utils/graphile/package.json, yarn.lock
- Fixes: https://github.com/graphile/crystal/issues/2663
- See: https://github.com/graphile/crystal/pull/2600
=> Overhaul optionality of peer dependencies to attempt to satisfy pnpm

.changeset/slimy-bags-smoke.md, graphile-build/graphile-build-pg/src/plugins/PgRBACPlugin.ts, postgraphile/postgraphile/__tests__/kitchen-sink-permissions.sql, postgraphile/postgraphile/__tests__/kitchen-sink-schema.sql, postgraphile/postgraphile/__tests__/schema/v4/relay.issue2334.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/relay.issue2334.1.graphql, postgraphile/postgraphile/__tests__/schema/v4/relay.issue2334.test.ts
=> Fix issue where PgRBACPlugin didn't handle nodeId:insert/update

.changeset/lucky-dolls-cover.md, graphile-build/graphile-build-pg/src/plugins/PgIndexBehaviorsPlugin.ts, postgraphile/postgraphile/__tests__/schema/v4/indexes.1.export.mjs, postgraphile/postgraphile/__tests__/schema/v4/indexes.1.graphql
=> Don't check views for indexes, they can't have any

.changeset/ninety-animals-ring.md, grafast/grafast/__tests__/onError-test.ts, grafast/grafast/src/bucket.ts, grafast/grafast/src/engine/OperationPlan.ts, grafast/grafast/src/engine/OutputPlan.ts, grafast/grafast/src/engine/executeOutputPlan.ts, grafast/grafast/src/establishOperationPlan.ts, grafast/grafast/src/grafastGraphql.ts, grafast/grafast/src/index.ts, grafast/grafast/src/interfaces.ts, grafast/grafast/src/prepare.ts, grafast/grafast/src/utils.ts, grafast/grafserv/src/interfaces.ts, grafast/grafserv/src/middleware/graphql.ts, grafast/grafserv/src/utils.ts, grafast/ruru-components/src/hooks/useFetcher.ts, grafast/ruru-components/src/hooks/useStorage.ts, grafast/ruru-components/src/ruru.tsx, postgraphile/postgraphile/graphile.config.ts, postgraphile/website/postgraphile/usage-schema.md
Implements the error behaviors part of https://github.com/graphql/graphql-spec/pull/1163
=> Add support for `onError` RFC

.changeset/pink-areas-sing.md, graphile-build/graphile-utils/__tests__/makeChangeNullabilityPlugin.test.ts, graphile-build/graphile-utils/src/makeChangeNullabilityPlugin.ts
=> Improve errors for changeNullability

.changeset/bright-clubs-flow.md, .changeset/five-hoops-sit.md, graphile-build/graphile-build/src/plugins/CommonTypesPlugin.ts, graphile-build/graphile-utils/__tests__/__snapshots__/makeExtendSchemaPlugin.test.ts.snap, graphile-build/graphile-utils/__tests__/makeExtendSchemaPlugin.test.ts, graphile-build/graphile-utils/src/makeExtendSchemaPlugin.ts
Implements:
- https://github.com/graphile/graphile-engine/pull/830
- https://github.com/graphile/graphile-engine/pull/821
=> Port more V4 PRs

grafast/website/grafast/access-control.mdx, grafast/website/grafast/plan-resolvers.mdx, grafast/website/grafast/step-classes.md, grafast/website/grafast/step-library/dataplan-pg/withPgClient.md, postgraphile/website/postgraphile/config.mdx, postgraphile/website/postgraphile/extend-schema.md
=> Overhaul the execute() docs

AGENTS.md, postgraphile/website/postgraphile/config.mdx, postgraphile/website/postgraphile/jwk-verification.md, postgraphile/website/postgraphile/jwt-guide.mdx, postgraphile/website/postgraphile/jwt-specification.md, postgraphile/website/postgraphile/security.md, postgraphile/website/sidebars.js
=> Overhaul V5 JWT/authn docs
